Repository wakmusic/wakmusic-iOS, pull requests merged in 2024-10, with the labels that each got.

#1305 🔀 :: (#1303) iPhone 16 model 추가
  Projects/Modules/Utility/Sources/Utils/Devices.swift
Labels: ⚡️ Simple, 3️⃣ Priority: Low

#1311 🔀 :: [#1309] Long Press 진입점의 UX가 비정상적인 이슈
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewModels/PlaylistViewModel.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
Labels: 🐞 Bug

#1313 🔀 :: (#1312) GitHub Action runner Xcode 버전 업그레이드
  .github/workflows/CI.yml
Labels: 🐞 Bug, ⚙ Setting

#1319 🔀 :: (#1317) 할로윈 스플래시 추가
  Package.resolved
  Package.swift
  Projects/Domains/AppDomain/Interface/Entity/AppCheckEntity.swift
  Projects/Domains/AppDomain/Sources/ResponseDTO/FetchAppCheckResponseDTO.swift
  Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
  Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
  Projects/Features/RootFeature/Sources/ViewModels/SplashLogoType.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Lottie/Splash_Logo_Halloween.json
  Projects/UsertInterfaces/DesignSystem/Resources/Lottie/Splash_Logo_Xmas.json
Labels: 1️⃣ Priority: High, ⚡️ Simple

#1318 🔀 :: (#1310) 재생목록, 나의 플리 swipe delete 구현
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewModels/PlaylistViewModel.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#1321 🔀 :: (#1320) 기간에 맞는 앱 아이콘 자동 변경
  Projects/App/Project.swift
  Projects/App/Resources/Assets.xcassets/HalloweenAppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/HalloweenAppIcon.appiconset/HalloweenAppIcon.png
  Projects/App/Resources/Assets.xcassets/XmasAppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/XmasAppIcon.appiconset/XmasAppIcon.png
  Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
  Projects/Features/RootFeature/Sources/ViewModels/SplashLogoType.swift
Labels: 1️⃣ Priority: High, ⚡️ Performance
