Repository wakmusic/wakmusic-iOS, pull requests merged in 2024-05, with the labels that each got.

#506 🔀 :: (#505) 디자인 시스템 신규 컬러 추가
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray100.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray200.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray25.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray300.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray400.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray50.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray500.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray600.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray700.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray800.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray900.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/NewGrayColor.xcassets/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/NewGrayColor.xcassets/gray400.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/NewGrayColor.xcassets/gray500.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/NewGrayColor.xcassets/gray600.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/NewGrayColor.xcassets/gray700.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/NewGrayColor.xcassets/gray900.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColor.xcassets/V1 SUB 1.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColor.xcassets/V1 SUB 2.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColor.xcassets/V1 SUB 3.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/BASE_SKELETON.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/DECREASE.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/HIGHLIGHT_SKELETON.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/INCREASE.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/NEW.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/POINT.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/SUB 1.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/SUB 2.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/TOAST.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/WAKTAVERSE.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/WHITE.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Sources/AliasBlueGray+Gray.swift
  Projects/UsertInterfaces/DesignSystem/Sources/AliasPrimaryV1+PrimaryV2.swift
Labels: 0️⃣ Priority: Critical, 🍱 Asset

#514 🔀 :: (#492) PlaylistDetail을 ReactorKit으로 리팩합니다.
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/Views/ArtistPlayButtonGroupView.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/BaseStoryboardReactorViewController.swift
  Projects/Features/BaseFeature/Sources/Views/PlayButtonGroupView.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/PlaylistFeature/Resources/Playlist.storyboard
  Projects/Features/PlaylistFeature/Sources/Components/PlayListDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Model/PlayListHeader.swift
  Projects/Features/PlaylistFeature/Sources/Model/PlaylistMetaData.swift
  Projects/Features/PlaylistFeature/Sources/PlayListDetailViewModel.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListDetailViewController.swift
Labels: ♻️ Refactor

#528 🔀 :: (#482) Privacy Manifest 작성
  Projects/App/Resources/PrivacyInfo.xcprivacy
Labels: 📃 Docs, 🌏 Deploy

#535 🔀 :: (#483) 음악 상세 화면 UI 작업
  .package.resolved
  Makefile
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Features/HomeFeature/Project.swift
  Projects/Features/MusicDetailFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MusicDetailFeature/Interface/Interface.swift
  Projects/Features/MusicDetailFeature/Project.swift
  Projects/Features/MusicDetailFeature/Sources/Analytics/MusicDetailAnalyticsLog.swift
  Projects/Features/MusicDetailFeature/Sources/Model/PlaylistModel.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetailReactor.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetailView.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetailViewController.swift
  Projects/Features/MusicDetailFeature/Sources/Views/MusicControlView/MusicControlGradientPanelLayer.swift
  Projects/Features/MusicDetailFeature/Sources/Views/MusicControlView/MusicControlView.swift
  Projects/Features/MusicDetailFeature/Sources/Views/MusicControlView/PlayMusicButtonGradientLayer.swift
  Projects/Features/MusicDetailFeature/Sources/Views/MusicDetailView/MusicDetailDimmedGradientLayer.swift
  Projects/Features/MusicDetailFeature/Sources/Views/MusicHeartButton/MusicHeartButton.swift
  Projects/Features/MusicDetailFeature/Sources/Views/MusicToolbarView.swift
  Projects/Features/MusicDetailFeature/Sources/Views/ThumbnailCollectionView/ThumbnailCell.swift
  Projects/Features/MusicDetailFeature/Sources/Views/ThumbnailCollectionView/ThumbnailCollectionView.swift
  Projects/Features/MusicDetailFeature/Tests/MusicDetailFeatureTest.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIStackView.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIView.swift
  Projects/Modules/Utility/Sources/Utils/Utils.swift
  Projects/Modules/Utility/Sources/Youtube/YoutubeURLGenerator.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Color/PrimaryColorV2.xcassets/POINT.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/credit.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/credit.imageset/credit.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/dismiss.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/dismiss.imageset/ic_32_close_header_fff.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/heart.fill.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/heart.fill.imageset/heart.fill.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/heart.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/heart.imageset/heart.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/lyrics.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/lyrics.imageset/lyrics.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/music_pick.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/music_pick.imageset/ic_32_playadd_25.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/next.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/next.imageset/ic_32_next_on.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/play.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/play.imageset/play.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/playlist.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/playlist.imageset/playlist.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/prev.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/prev.imageset/ic_32_prev_on.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/singing_room.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/singing_room.imageset/singing_room.svg
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/views.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/views.imageset/views.svg
  Projects/UsertInterfaces/DesignSystem/Sources/VerticalAlignButton.swift
  Projects/UsertInterfaces/DesignSystem/Sources/WMLabel.swift
  Projects/UsertInterfaces/DesignSystem/Sources/WMNavigationBarView.swift
  Tuist/Package.resolved
  Tuist/ProjectDescriptionHelpers/Action+Template.swift
Labels: ✨ Feature

#547 🔀 :: (#546) Artist Domain 변경점 적용 2nd
  Projects/Domains/ArtistDomain/Sources/ResponseDTO/ArtistListResponseDTO.swift
Labels: ⚡️ Simple

#545 🔀 :: (#544) Chart Domain 변경점 적용 2nd
  Projects/App/Sources/Application/AppComponent+Chart.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domains/ArtistDomain/Sources/ResponseDTO/ArtistListResponseDTO.swift
  Projects/Domains/ChartDomain/Interface/DataSource/RemoteChartDataSource.swift
  Projects/Domains/ChartDomain/Interface/Entity/ChartEntity.swift
  Projects/Domains/ChartDomain/Interface/Repository/ChartRepository.swift
  Projects/Domains/ChartDomain/Interface/UseCase/FetchChartRankingUseCase.swift
  Projects/Domains/ChartDomain/Interface/UseCase/FetchChartUpdateTimeUseCase.swift
  Projects/Domains/ChartDomain/Sources/API/ChartAPI.swift
  Projects/Domains/ChartDomain/Sources/DataSource/RemoteChartDataSourceImpl.swift
  Projects/Domains/ChartDomain/Sources/Repository/ChartRepositoryImpl.swift
  Projects/Domains/ChartDomain/Sources/ResponseDTO/FetchChartRankingResponseDTO.swift
  Projects/Domains/ChartDomain/Sources/UseCase/FetchChartRankingUseCaseImpl.swift
  Projects/Domains/ChartDomain/Sources/UseCase/FetchChartUpdateTimeUseCaseImpl.swift
  Projects/Features/ChartFeature/Sources/Components/ChartContentComponent.swift
  Projects/Features/ChartFeature/Sources/ViewModels/ChartContentViewModel.swift
  Projects/Features/HomeFeature/Sources/Components/NewSongsContentComponent.swift
  Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
  Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
Labels: ⚡️ Simple

#543 🔀 :: (#542) 사용하지 않는 Google Secret 제거
  Projects/App/Support/Info.plist
  Projects/Modules/Utility/Sources/GoogleOAuth/GoogleLoginManager.swift
  Projects/Modules/Utility/Sources/Utils/Secrets.swift
Labels: 0️⃣ Priority: Critical, 🌏 Deploy, ⚙ Setting

#555 🔀 :: (#554) pre-push 시점에 SwiftFormat 적용
  .githooks/pre-push
  Cartfile
Labels: ⚡️ Simple, 2️⃣ Priority: Medium, ⚙ Setting
