Repository wakmusic/wakmusic-iOS, pull requests merged in 2024-08, with the labels that each got.

#936 🔀 :: (#935) 팀 소개:: 최종
  Projects/Domains/TeamDomain/Interface/Entity/TeamListEntity.swift
  Projects/Domains/TeamDomain/Sources/ResponseDTO/FetchTeamListResponseDTO.swift
  Projects/Features/TeamFeature/Sources/ViewControllers/TeamInfoContentViewController.swift
  Projects/Features/TeamFeature/Sources/ViewModels/TeamInfoContentViewModel.swift
  Projects/Features/TeamFeature/Sources/ViewModels/TeamInfoViewModel.swift
  Projects/Features/TeamFeature/Sources/Views/TeamInfoHeaderView.swift
  Projects/Features/TeamFeature/Sources/Views/TeamInfoListCell.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#934 🔀 :: (#933) 아티스트 상세:: 전체재생 기능
  Projects/Domains/ArtistDomain/Interface/Entity/ArtistListEntity.swift
  Projects/Domains/ArtistDomain/Sources/ResponseDTO/ArtistListResponseDTO.swift
  Projects/Features/ArtistFeature/Sources/Reactors/ArtistReactor.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
  Projects/Features/ArtistFeature/Tests/ArtistReactorTests.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#920 🔀 :: (#895) 로그인 여부에 따라 자동으로 my/unkwown 플레이리스트 스위칭
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/Domains/PlaylistDomain/Interface/DataSource/RemotePlaylistDataSource.swift
  Projects/Domains/PlaylistDomain/Interface/Entity/PlaylistOwnerIDEntity.swift
  Projects/Domains/PlaylistDomain/Interface/Repository/PlaylistRepository.swift
  Projects/Domains/PlaylistDomain/Interface/UseCase/RequestPlaylistOwnerIDUsecase.swift
  Projects/Domains/PlaylistDomain/Sources/API/PlaylistAPI.swift
  Projects/Domains/PlaylistDomain/Sources/DataSource/RemotePlaylistDataSourceImpl.swift
  Projects/Domains/PlaylistDomain/Sources/Repository/PlaylistRepositoryImpl.swift
  Projects/Domains/PlaylistDomain/Sources/ResponseDTO/PlaylistOwnerIdResponseDTO.swift
  Projects/Domains/PlaylistDomain/Sources/UseCase/RequestPlaylistOwnerIDUsecaseImpl.swift
  Projects/Domains/SearchDomain/Interface/Entity/SearchPlaylistEntity.swift
  Projects/Domains/SearchDomain/Sources/DTO/SearchPlaylistDTO.swift
  Projects/Features/BaseFeature/Sources/Views/SongCartView.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/PlaylistFeature/Interface/PlaylistDetailFactory.swift
  Projects/Features/PlaylistFeature/Interface/PlaylistDetailNavigator.swift
  Projects/Features/PlaylistFeature/Project.swift
  Projects/Features/PlaylistFeature/Sources/Components/PlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/UnkwonPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistDetailContainerReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistDetailContainerViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Testing/PlaylistDetailFactoryStub.swift
  Projects/Features/SearchFeature/Project.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
Labels: 1️⃣ Priority: High, ⚡️ Performance

#941 🔀 :: (#940) 아티스트 상세:: 노래담기 비로그인 처리
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/Domains/PlaylistDomain/Sources/API/PlaylistAPI.swift
  Projects/Domains/PlaylistDomain/Sources/DataSource/RemotePlaylistDataSourceImpl.swift
  Projects/Domains/PlaylistDomain/Sources/Repository/PlaylistRepositoryImpl.swift
  Projects/Domains/PlaylistDomain/Sources/ResponseDTO/PlaylistOwnerIdResponseDTO.swift
  Projects/Features/ArtistFeature/Sources/Components/ArtistMusicContentComponent.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/PlaylistFeature/Interface/PlaylistDetailNavigator.swift
  Projects/Features/PlaylistFeature/Sources/Components/PlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/UnkwonPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistDetailContainerReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistDetailContainerViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Testing/PlaylistDetailFactoryStub.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, ✨ Feature

#919 🔀 :: (#918) 작업자 노래 리스트 화면에서 상단 Gradient가 표시되지 않는 이슈 해결
  Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#922 🔀 :: (#912) 재생목록 화면 인터렉션 및 UI 반영
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailView.swift
  Projects/Features/PlaylistFeature/Sources/Components/PlaylistComponent.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/PlayListView.swift
  Projects/Features/PlaylistFeature/Sources/Views/PlaylistTableViewCell.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#923 🔀 :: (#911) PlayState 인터페이스 정리
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
Labels: 0️⃣ Priority: Critical, ♻️ Refactor

#926 🔀 :: (#925) Credit Page UI 정상화
  Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
  Projects/Features/SongCreditFeature/Sources/View/CreditCollectionView/CreditCollectionViewLayout.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#931 🔀 :: (#899) 음악 상세 페이지 음악 제목, 아티스트 WMLabel -> WMFlowLabel 전환
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicControlView/MusicControlView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/WMFlowLabel.swift
Labels: ⚡️ Simple, 2️⃣ Priority: Medium

#898 🔀 :: (#848) 닉네임 변경 및 열매 뽑기 반응 구현
  Projects/Features/MyInfoFeature/Sources/Components/MyInfoComponent.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/FruitDrawButtonView.swift
  Projects/Features/MyInfoFeature/Sources/Views/MyInfoView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#930 🔀 :: (#809, #929, #927) 좋아요 로직 구현
  Projects/App/Sources/Application/AppComponent+Songs.swift
  Projects/Domains/LikeDomain/Interface/DataSource/RemoteLikeDataSource.swift
  Projects/Domains/LikeDomain/Interface/Repository/LikeRepository.swift
  Projects/Domains/LikeDomain/Project.swift
  Projects/Domains/LikeDomain/Sources/API/LikeAPI.swift
  Projects/Domains/LikeDomain/Sources/DataSource/Remote/RemoteLikeDataSourceImpl.swift
  Projects/Domains/LikeDomain/Sources/Repository/LikeRepositoryImpl.swift
  Projects/Domains/LikeDomain/Sources/ResponseDTO/CheckIsLikedResponseDTO.swift
  Projects/Domains/LikeDomain/Testing/UseCase/AddLikeSongUseCaseSpy.swift
  Projects/Domains/LikeDomain/Testing/UseCase/CancelLikeSongUseCaseSpy.swift
  Projects/Domains/SongsDomain/Interface/Entity/SongDetailEntity.swift
  Projects/Domains/SongsDomain/Interface/UseCase/FetchSongUseCase.swift
  Projects/Domains/SongsDomain/Project.swift
  Projects/Domains/SongsDomain/Sources/API/SongsAPI.swift
  Projects/Domains/SongsDomain/Sources/UseCase/FetchSongUseCaseImpl.swift
  Projects/Domains/SongsDomain/Testing/UseCase/FetchSongUseCaseSpy.swift
  Projects/Domains/UserDomain/Interface/Entity/FavoriteSongEntity.swift
  Projects/Domains/UserDomain/Project.swift
  Projects/Domains/UserDomain/Sources/Repository/UserRepositoryImpl.swift
  Projects/Domains/UserDomain/Sources/ResponseDTO/FavoriteSongsResponseDTO.swift
  Projects/Domains/UserDomain/Testing/FetchFavoriteSongsUseCaseStub.swift
  Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MusicDetailFeature/Project.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Component/MusicDetailComponent.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Model/SongModel.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailView.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicToolbarView.swift
  Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Views/LikeStorageTableViewCell.swift
  Projects/Modules/Utility/Sources/Realm/RealmManager.swift
Labels: ✨ Feature

#952 🔀 :: (#949, #791) 프로필 변경 기능 구현 외1
  Projects/App/Sources/Application/AppComponent+MyInfo.swift
  Projects/Features/MyInfoFeature/Interface/Protocol/Factory.swift
  Projects/Features/MyInfoFeature/Resources/Notice.storyboard
  Projects/Features/MyInfoFeature/Resources/ProfilePopUp.storyboard
  Projects/Features/MyInfoFeature/Resources/Question.storyboard
  Projects/Features/MyInfoFeature/Sources/Components/MyInfoComponent.swift
  Projects/Features/MyInfoFeature/Sources/Components/ProfilePopComponent.swift
  Projects/Features/MyInfoFeature/Sources/Components/ProfilePopupComponent.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/ProfilePopup/ProfilePopViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/ProfilePopup/ProfilePopupViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/NoticeDetailViewModel.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/ProfilePopViewModel.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/ProfilePopupViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Views/FruitDrawButtonView.swift
  Projects/Features/MyInfoFeature/Sources/Views/MyInfoView.swift
  Projects/Features/MyInfoFeature/Sources/Views/ProfileCollectionViewCell.swift
  Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extension+UILabel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#956 🔀 :: (#954, #955) 불필요 로직 제거
  Projects/Features/FruitDrawFeature/Sources/Components/FruitDrawComponent.swift
  Projects/Features/FruitDrawFeature/Sources/ViewModels/FruitDrawViewModel.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
  Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
  Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Performance

#962 🔀 :: (#959) 차트, 최신음악 > 비로그인 시 노래 담기 액션 처리
  Projects/Features/ChartFeature/Project.swift
  Projects/Features/ChartFeature/Sources/Components/ChartContentComponent.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/ChartFeature/Sources/ViewModels/ChartContentViewModel.swift
  Projects/Features/HomeFeature/Project.swift
  Projects/Features/HomeFeature/Sources/Components/NewSongsContentComponent.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature, 🐞 Bug

#963 🔀 :: (#961) 내 정보:: 로그인/아웃 시 열매 카운트 갱신
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/Views/FruitDrawButtonView.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#967 🔀 :: (#965) Preference.useInfo 저장 로직 레파지토리로 이동
  Projects/Domains/UserDomain/Sources/Repository/UserRepositoryImpl.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Performance

#964 🔀 :: (#932) 음악 좋아요 비로그인 처리
  Projects/Features/CreditSongListFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/CreditSongListFeature/Project.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/Component/CreditSongListTabItemComponent.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
  Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MusicDetailFeature/Project.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Component/MusicDetailComponent.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
  Projects/Modules/Utility/Sources/GoogleOAuth/GoogleLoginManager.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature, 🐞 Bug

#966 🔀 :: (#924) CI 속도 개선
  .github/workflows/CI.yml
  Tuist/Signing/WaktaverseMusic.Debug.cer.encrypted
  Tuist/Signing/WaktaverseMusic.Debug.mobileprovision
  Tuist/Signing/WaktaverseMusic.Debug.p12.encrypted
  Tuist/Signing/WaktaverseMusic.Release.cer.encrypted
  Tuist/Signing/WaktaverseMusic.Release.mobileprovision
  Tuist/Signing/WaktaverseMusic.Release.p12.encrypted
Labels: 0️⃣ Priority: Critical, ⚡️ Performance, ⚙ Setting

#972 🔀 :: (#971) 플레이리스트 디테일 컨테이너에 로그인 갱신 로직을 변경해요
  Projects/Domains/AuthDomain/Sources/UseCase/FetchTokenUseCaseImpl.swift
  Projects/Domains/AuthDomain/Sources/UseCase/LogoutUseCaseImpl.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistDetailContainerViewController.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/StorageReactor.swift
  Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift
Labels: 1️⃣ Priority: High

#980 🔀 :: (#968) 가사 하이라이팅 > 자막 제공 UI 추가
  Projects/Domains/SongsDomain/Interface/DataSource/RemoteSongsDataSource.swift
  Projects/Domains/SongsDomain/Interface/Entity/LyricsEntity.swift
  Projects/Domains/SongsDomain/Interface/Repository/SongsRepository.swift
  Projects/Domains/SongsDomain/Interface/UseCase/FetchLyricsUseCase.swift
  Projects/Domains/SongsDomain/Sources/DataSource/RemoteSongsDataSourceImpl.swift
  Projects/Domains/SongsDomain/Sources/Repository/SongsRepositoryImpl.swift
  Projects/Domains/SongsDomain/Sources/ResponseDTO/LyricsResponseDTO.swift
  Projects/Domains/SongsDomain/Sources/UseCase/FetchLyricsUseCaseImpl.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController+Bind.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController+Bind.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
  Projects/Features/LyricHighlightingFeature/Sources/Views/LyricHighlightingCell.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature, 🚀 API

#979 🔀 :: (#976) 열매 소비가 필요한 로직 이후 유저정보를 갱신합니다.
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/Service/MyInfoCommonService.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#982 🔀 :: (#981) 인트로(스플래쉬) > 유저정보 api 호출 제거
  Projects/Domains/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domains/AuthDomain/Interface/UseCase/LogoutUseCase.swift
  Projects/Domains/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domains/AuthDomain/Sources/UseCase/LogoutUseCaseImpl.swift
  Projects/Domains/AuthDomain/Testing/LogoutUseCaseSpy.swift
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/SettingReactor.swift
  Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
  Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Performance

#987 🔀 :: (#984) 재생목록 페이지에서 모든 노래를 삭제가 불가능한 이슈 해결
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewModels/PlayListViewModel.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#988 🔀 :: (#769) 보관함 플레이리스트를 현재 재생목록에 추가하는 기능들 구현
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/Domains/PlaylistDomain/Interface/DataSource/RemotePlaylistDataSource.swift
  Projects/Domains/PlaylistDomain/Interface/Repository/PlaylistRepository.swift
  Projects/Domains/PlaylistDomain/Sources/DataSource/RemotePlaylistDataSourceImpl.swift
  Projects/Domains/PlaylistDomain/Sources/Repository/PlaylistRepositoryImpl.swift
  Projects/Domains/PlaylistDomain/Sources/UseCase/FetchPlaylistSongsUseCaseImpl.swift
  Projects/Features/StorageFeature/Sources/Components/LikeStorageComponent.swift
  Projects/Features/StorageFeature/Sources/Components/ListStorageComponent.swift
  Projects/Features/StorageFeature/Sources/Components/StorageComponent.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#991 🔀 :: (#985) 50곡 제한 토스트 누락 토스트 명시
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
Labels: 🐞 Bug, 2️⃣ Priority: Medium

#992 🔀 :: (#990) 내 정보 viewDidLoad 시 서버로부터 유저정보 fetch
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/Service/MyInfoCommonService.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#994 🔀 :: (#986) 재생목록 편집 상태 동기화
  Projects/Features/PlaylistFeature/Sources/Components/PlaylistComponent.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewModels/PlayListViewModel.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#995 🔀 :: (#993) 열매 갯수 변동 시 내 정보에 바로 반영되지 않는 문제 수정
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#996 🔀 :: (#890) 좋아요 탭에서 썸네일 클릭 시 노래 상세로 이동
  Projects/Features/StorageFeature/Sources/Components/LikeStorageComponent.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
  Projects/Features/StorageFeature/Sources/Views/LikeStorageTableViewCell.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#997 🔀 :: (#978) 앱이 실행되자마자 보관함을 갱신하는 문제 수정
  Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Performance, 🐞 Bug

#999 🔀 :: (#998) 음악 상세 UI 제약조건 변경
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailView.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicToolbarView.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#1000 🔀 :: (#977) 보관함 리스트 생성 시 음표 열매 소모
  Projects/App/Sources/Application/AppComponent+Price.swift
  Projects/Domains/PriceDomain/Interface/UseCase/FetchPlaylistCreationPriceUseCase.swift
  Projects/Domains/PriceDomain/Interface/UseCase/FetchPlaylistImagePriceUseCase.swift
  Projects/Domains/PriceDomain/Sources/UseCase/FetchPlaylistCreationPriceUseCaseImpl.swift
  Projects/Domains/PriceDomain/Sources/UseCase/FetchPlaylistImagePriceUseCaseImpl.swift
  Projects/Features/BaseFeature/Sources/Components/ContainSongsComponent.swift
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/PlaylistFeature/Sources/Components/PlaylistCoverOptionPopupComponent.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistCoverOptionPopupReactor.swift
  Projects/Features/StorageFeature/Sources/Components/ListStorageComponent.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#1029 🔀 :: (#1027) 키보드 입력화면의 enum 정리 및 개선
  Projects/Features/BaseFeature/Interface/Enum/PurposeType.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
Labels: 1️⃣ Priority: High

#1031 🔀 :: (#1024) 뮤직 디테일 present 방식 변경
  Projects/Features/HomeFeature/Project.swift
  Projects/Features/HomeFeature/Sources/Components/HomeComponent.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/PlaylistFeature/Project.swift
  Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/UnkwonPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/WakmusicPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
  Projects/Features/SearchFeature/Project.swift
  Projects/Features/SearchFeature/Sources/After/Components/SongSearchResultComponent.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
Labels: 1️⃣ Priority: High

#1032 🔀 :: (#1020) 최신음악:: 전체재생 기능 추가
  Projects/App/Sources/Application/AppComponent+Songs.swift
  Projects/Domains/SongsDomain/Interface/DataSource/RemoteSongsDataSource.swift
  Projects/Domains/SongsDomain/Interface/Entity/NewSongsPlaylistEntity.swift
  Projects/Domains/SongsDomain/Interface/Repository/SongsRepository.swift
  Projects/Domains/SongsDomain/Interface/UseCase/FetchNewSongsPlaylistUseCase.swift
  Projects/Domains/SongsDomain/Sources/API/SongsAPI.swift
  Projects/Domains/SongsDomain/Sources/DataSource/RemoteSongsDataSourceImpl.swift
  Projects/Domains/SongsDomain/Sources/Repository/SongsRepositoryImpl.swift
  Projects/Domains/SongsDomain/Sources/ResponseDTO/NewSongsPlaylistResponseDTO.swift
  Projects/Domains/SongsDomain/Sources/UseCase/FetchNewSongsPlaylistUseCaseImpl.swift
  Projects/Features/HomeFeature/Sources/Components/NewSongsContentComponent.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1035 🔀 :: (#1013) 푸시 토큰 등록 오류 의심 로직 제거
  Projects/Features/MainTabFeature/Sources/ViewModels/MainTabBarViewModel.swift
Labels: 🐞 Bug, 3️⃣ Priority: Low

#1033 🔀 :: (#1021) 음악 상세에서 노래 재생 시 플리에 추가
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1036 🔀 :: (#1016, 1017) 재생목록 토스트 메시지 오류 수정
  Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
  Projects/Features/PlaylistFeature/Interface/PlaylistCoverOptionPopupFactory.swift
  Projects/Features/PlaylistFeature/Sources/Model/PlaylistCoverOptionModel.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistCoverOptionPopupReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistCoverOptionViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/ThumbnailOptionTableViewCell.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Modules/Localization/Resources/en.lproj/Localizable.strings
  Projects/Modules/Localization/Resources/ko.lproj/Localizable.strings
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1038 🔀 :: (#978) 내정보화면에서 불필요한 api가 호출되던 문제 수정
  Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Performance, 🐞 Bug

#1042 🔀 :: (#1041) 스와이프 백 제스쳐 추가
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
Labels: 3️⃣ Priority: Low

#1044 🔀 :: (#1043) 네비 우측 버튼 내 간격 추가
  Projects/UsertInterfaces/DesignSystem/Sources/WMNavigationBarView.swift
Labels: 3️⃣ Priority: Low

#1049 🔀 :: (#1046) 플레이리시트 컨테이너 로딩 중 처리
  Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistDetailContainerReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistDetailContainerViewController.swift
Labels: 2️⃣ Priority: Medium

#1051 🔀 :: (#1048) 아티스트:: Retry UI 추가
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/WakmusicPlaylistDetailReactor.swift
  Projects/Features/SearchFeature/Sources/After/Reactors/ListSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/After/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/Before/Reactors/BeforeSearchReactor.swift
  Projects/Features/SearchFeature/Sources/Before/Reactors/WakmusicRecommendReactor.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Modules/Localization/Resources/en.lproj/Localizable.strings
  Projects/Modules/Localization/Resources/ko.lproj/Localizable.strings
  Projects/UsertInterfaces/DesignSystem/Sources/WMRetryWarningView.swift
Labels: 2️⃣ Priority: Medium

#1050 🔀 :: (#1001) 비로그인 상태에서 토큰이 필요한 api를 요청하면, 토큰을 재발급하려고 시도하는 문제
  Projects/Domains/BaseDomain/Sources/DataSource/BaseRemoteDataSource.swift
Labels: 1️⃣ Priority: High

#1052 🔀 :: (#1009) 팀 정보:: UI 초기화 되는 문제 수정
  Projects/Features/TeamFeature/Sources/Views/TeamInfoSectionView.swift
Labels: 🐞 Bug, 3️⃣ Priority: Low

#1056 🔀 :: (#1054) 비 로그인 시 무한로딩 버그 해결
  Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistDetailContainerReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistDetailContainerViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1053 🔀 :: (#1047) 음악 상세에서 좋아요 클릭 시 보관함 좋아요 페이지 리스트 갱신
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift
Labels: 2️⃣ Priority: Medium

#1058 🔀 :: (#1057) 플로팅 버튼 탭에 따른 위치 조절
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift
Labels: 1️⃣ Priority: High

#1059 🔀 :: (#826) 사용하지 않는 project 셋팅관련 코드 제거
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/PathExtension.swift
  Projects/App/Project.swift
  Projects/Domains/BaseDomain/Project.swift
  Projects/Features/BaseFeature/Project.swift
  Scripts/GeneteFeature/Project.swift
  Scripts/GeneteFeature/Sources/Feature.swift
  Scripts/GeneteFeature/Tests/.gitkeep
  Scripts/GeneteFeature/Tests/TargetTest.swift
  Scripts/generate_new_feature.py
Labels: ⚡️ Simple, 3️⃣ Priority: Low

#1060 🔀 :: (#970) 노티피케이션 이름 정리
  Projects/Features/BaseFeature/Sources/Protocols/EditSheetViewType.swift
  Projects/Features/BaseFeature/Sources/Protocols/PlaylistEditSheetViewType.swift
  Projects/Features/BaseFeature/Sources/Protocols/SongCartViewType.swift
  Projects/Features/BaseFeature/Sources/Protocols/WMBottomSheetViewType.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
  Projects/Features/BaseFeature/Sources/Views/WMBottomSheetView.swift
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitStorageViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/BottomTabBarViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
  Projects/Features/MainTabFeature/Sources/Views/TabItemView.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/Service/PlaylistCommonService.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/PlayListView.swift
  Projects/Features/SearchFeature/Sources/Root/ViewControllers/SearchViewController.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift
Labels: 2️⃣ Priority: Medium, ♻️ Refactor

#1062 🔀 :: (#1061) 건의 사항 참여정보 항목 추가
  Projects/Features/MyInfoFeature/Resources/Question.storyboard
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Question/QuestionViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/QuestionViewModel.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#1065 🔀 :: (#1063) 재생목록에 곡이 없을 시 FAB 버튼 숨김 처리
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewModels/PlayListViewModel.swift
Labels: ✨ Feature, 2️⃣ Priority: Medium

#1066 🔀 :: (#1064) Credit -> 아티스트 화면 진입을 위한 Credit API 변경사항 반영
  Projects/Domains/SongsDomain/Interface/Entity/SongCreditsEntity.swift
  Projects/Domains/SongsDomain/Sources/ResponseDTO/SongCreditsResponseDTO.swift
  Projects/Features/SongCreditFeature/Sources/Model/CreditModel.swift
  Projects/Features/SongCreditFeature/Sources/SongCreditReactor.swift
  Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#1070 🔀 :: (#1069) 아티스트 상세:: 크레딧에서 접근한 경우 노래 썸네일이 눌리지않는 오류 수정 외 2
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitDrawViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Question/QuestionViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/QuestionViewModel.swift
Labels: 🐞 Bug, 3️⃣ Priority: Low

#1073 🔀 :: (#1072) 열매뽑기:: 오늘 뽑기 완료 상태로 뽑기버튼을 누르면 토스트 추가
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitDrawViewController.swift
  Projects/Features/FruitDrawFeature/Sources/ViewModels/FruitDrawViewModel.swift
Labels: 2️⃣ Priority: Medium

#1079 🔀 :: (#1078) 최신음악:: 전체재생 버튼 텍스트의 센터정렬이 맞지않음
  Projects/UsertInterfaces/DesignSystem/Sources/SingleActionButtonView.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#1077 🔀 :: (#1076) 가사꾸미기:: 네트워크 실패 오류가 노출되는 현상
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController+Bind.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1075 🔀 :: (#1074) 자주묻는질문:: 카테고리가 전체만 노출되는 오류 수정
  Projects/Domains/FaqDomain/Sources/DataSource/RemoteFaqDataSourceImpl.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/FAQ/FaqContentViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1088 🔀 :: (#1087) CI workflow 트리거 조건 변경
  .github/workflows/CI.yml
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1086 🔀 :: (#1083) Credit 노래 리스트 상단 Gradient 영역 조정
  Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1084 🔀 :: (#1082) 크레딧 로딩 인디케이터 동작 오류 이슈 해결
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1090 🔀 :: (#1089) 문의하기 참여정보 -> 참여 정보 텍스트 변경
  Projects/Features/MyInfoFeature/Sources/ViewModels/QuestionViewModel.swift
Labels: ⚡️ Simple, 3️⃣ Priority: Low

#1092 🔀 :: (#1071) 검색 화면에서 바로 빠져나갈 수 있는 동작
  Projects/Features/SearchFeature/Sources/Root/ViewControllers/SearchViewController.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Performance

#1094 🔀 :: (#1093) 더보기 버튼을 통해 하단 뷰 숨기기
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#1096 🔀 :: (#1091) private 플리 접근 처리
  Projects/Features/PlaylistFeature/Sources/Components/PlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/UnkwonPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistDetailContainerReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistDetailContainerViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1097 🔀 :: (#1095) 토스트 테마 확장
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController+Bind.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
Labels: 1️⃣ Priority: High

#1100 🔀 :: (#1099) Credit 로딩 인디케이터가 불필요한 상황에 표시되는 이슈 해결
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1098 🔀 :: (#1085) 홈화면 Translucent 적용
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#1102 🔀 :: (#1101) 보관함 - 좋아요 창에서도 제목부분 클릭시 곡 상세로 가도록
  Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
  Projects/Features/StorageFeature/Sources/Views/LikeStorageTableViewCell.swift
  Projects/Features/StorageFeature/Sources/Views/LikeStorageView.swift
Labels: 1️⃣ Priority: High

#1104 🔀 :: (#1103) 디폴트 이미지 변경 반영 및 플리 변경사항 저장 스로틀 적용
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1107 🔀 :: (#1106) 참여정보:: 크롤링 이슈로 들어오는 공백 문자열 처리
  Projects/Features/SongCreditFeature/Sources/SongCreditReactor.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1108 🔀 :: (#1105) My 플리 저장 시 인디케이터 작업
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#1111 🔀 :: (#1110) 노래 상세 페이지 제목 <-> 아티스트 간 텍스트 공백 추가
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicControlView/MusicControlView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#1120 🔀 :: (#1112) develop이 아닌 브랜치를 대상으로 PR 머지 시 연관된 이슈 자동으로 close
  .github/PULL_REQUEST_TEMPLATE.md
  .github/actions/Auto_close_associate_issue/Dockerfile
  .github/actions/Auto_close_associate_issue/action.yml
  .github/actions/Auto_close_associate_issue/main.js
  .github/workflows/AutoCloseIssueByPullRequest.yml
Labels: 2️⃣ Priority: Medium, ⚙ Setting

#1124 🔀 :: (#1123) PR merge시 연관 이슈 자동 close가 동작하지 않는 이슈
  .github/workflows/AutoCloseIssueByPullRequest.yml
Labels: 3️⃣ Priority: Low, ⚙ Setting

#1122 🔀 :: (#1121) 네트워크 로그를 디테일/간소화 로 분기처리
  Projects/App/Project.swift
  Projects/Domains/BaseDomain/Sources/Logging/CustomLoggingPlugin.swift
Labels: ♻️ Refactor, 3️⃣ Priority: Low

#1126 🔀 :: (#1125) AutoCloseIssueByPullRequest workflow가 실행되지 않음
  .github/workflows/AutoCloseIssueByPullRequest.yml
Labels: 🐞 Bug, 3️⃣ Priority: Low

#1128 🔀 :: (#1127) 리드미 수정
  README.md
Labels: 3️⃣ Priority: Low, ⚙ Setting

#1132 🔀 :: (#1129) 음악 상세 노래방 번호 표시가 안되는 이슈 해결
  Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Component/MusicDetailComponent.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Model/SongModel.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1133 🔀 :: (#1131) 마이페이지 열매 버튼 배경색 변경
  Projects/Features/MyInfoFeature/Sources/Views/FruitDrawButtonView.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#1134 🔀 :: (#1114) 마이 페이지 프로필 버튼 bouncy 이펙트 추가
  Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#1136 🔀 :: (#1135) 크레딧 작업자 프로필 이미지 지원
  Projects/App/Sources/Application/AppComponent+Credit.swift
  Projects/Domains/CreditDomain/Interface/DataSource/RemoteCreditDataSource.swift
  Projects/Domains/CreditDomain/Interface/Repository/CreditRepository.swift
  Projects/Domains/CreditDomain/Interface/UseCase/FetchCreditProfileImageURLUseCase.swift
  Projects/Domains/CreditDomain/Sources/API/CreditAPI.swift
  Projects/Domains/CreditDomain/Sources/DataSource/RemoteCreditDataSourceImpl.swift
  Projects/Domains/CreditDomain/Sources/Repository/CreditRepositoryImpl.swift
  Projects/Domains/CreditDomain/Sources/ResponseDTO/FetchCreditProfileImageURLResponseDTO.swift
  Projects/Domains/CreditDomain/Sources/UseCase/FetchCreditProfileImageURLUseCaseImpl.swift
  Projects/Domains/CreditDomain/Testing/UseCase/FetchCreditProfileImageURLUseCaseSpy.swift
  Projects/Features/CreditSongListFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongList/Component/CreditSongListComponent.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListReactor.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongList/View/CreditProfileView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#1144 🔀 :: (#1130) 보관함 플레이리스트를 재생했을 때 첫 곡만 재생되던 문제 수정
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1141 🔀 :: (#1137) 마이페이지 내 열매 버튼 border color 변경
  Projects/Features/MyInfoFeature/Sources/Views/FruitDrawButtonView.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple, ✨ Feature

#1142 🔀 :: (#1138) 아티스트 리스트 페이지 translucent 적용
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#1143 🔀 :: (#1139) 회원탈퇴 버튼에서 '여기' 텍스트 이외에도 탈퇴 동작이 이루어짐
  Projects/Features/BaseFeature/Interface/TextPopUp/TextPopUpFactory.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/WithDrawLabel.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1152 🔀 :: (#1140) 홈, 검색, 아티스트 탭 로그 수집
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ChartFeature/Sources/Analytics/ChartAnalyticsLog.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListViewController.swift
  Projects/Features/HomeFeature/Sources/Analytics/HomeAnalyticsLog.swift
  Projects/Features/HomeFeature/Sources/Analytics/NewSongsAnalyticsLog.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsViewController.swift
  Projects/Features/MainTabFeature/Sources/Analytics/MainTabAnalyticsLog.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/BottomTabBarViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
  Projects/Features/MainTabFeature/Sources/Views/TabItemView.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/AfterSearchViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/Root/ViewControllers/SearchViewController.swift
  Projects/Features/SongCreditFeature/Sources/Analytics/SongCreditAnalyticsLog.swift
  Projects/Features/SongCreditFeature/Sources/SongCreditReactor.swift
  Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
  Projects/Modules/LogManager/Sources/CommonAnalyticsLog.swift
Labels: 0️⃣ Priority: Critical, 🌏 Deploy

#1147 🔀 :: (#950) 좋아요 로직 고도화
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
Labels: ⚡️ Performance, 2️⃣ Priority: Medium

#1157 🔀 :: (#1156) 아티스트 선택이 안됨
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1159 🔀 :: (#1158) 아티스트 선택이 안됨 2t
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1169 🔀 :: (#1168) 푸시발송 이스터에그 위치 변경
  Projects/Features/ArtistFeature/Resources/Artist.storyboard
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Labels: 0️⃣ Priority: Critical

#1151 🔀 :: (#1148) 검색 결과 로딩 중 필터나 정렬을 누를 때 앱이 터지는 버그
  Projects/Features/SearchFeature/Sources/After/Reactors/ListSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/After/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1174 🔀 :: (#1171) QA Configuration 추가
  Package.swift
  Plugin/ConfigurationPlugin/ProjectDescriptionHelpers/Configuration+Ext.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/Domains/BaseDomain/Sources/DataSource/BaseRemoteDataSource.swift
  Projects/Domains/BaseDomain/Sources/Logging/CustomLoggingPlugin.swift
  Projects/Domains/BaseDomain/Sources/WMAPI/SecretURL.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Request/RequestViewController.swift
  Projects/Modules/LogManager/Sources/AnalyticsLogManager.swift
  Projects/Modules/LogManager/Sources/LogHistory/LogHistoryCell.swift
  Projects/Modules/LogManager/Sources/LogHistory/LogHistorySectionItem.swift
  Projects/Modules/LogManager/Sources/LogHistory/LogHistoryStorage.swift
  Projects/Modules/LogManager/Sources/LogHistory/LogHistoryViewController.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
  Projects/Modules/Utility/Sources/Utils/Utils.swift
Labels: 1️⃣ Priority: High, ⚙ Setting

#1179 🔀 :: (#1176) 공지팝업 홀쭉해진 오류 수정
  Projects/Features/MainTabFeature/Resources/Main.storyboard
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/NoticePopupViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1177 🔀 :: (#1172) 노래 상세로 진입 시 재생목록에 추가
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#1175 🔀 :: (#1173) 재생목록 최대 제한 해제
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/RandomPlayButtonGroupView.swift
  Projects/Features/PlaylistFeature/Sources/Views/RandomPlayButtonHeaderView.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#1178 🔀 :: (#1166) 홈화면 로그 수정 반영
  Projects/Features/HomeFeature/Sources/Analytics/HomeAnalyticsLog.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#1182 🔀 :: (#1149) 내 정보, 설정화면 애널리틱스 로그 심기
  Projects/Features/MyInfoFeature/Sources/Analytics/MyInfoAnalyticsLog.swift
  Projects/Features/MyInfoFeature/Sources/Analytics/SettingAnalyticsLog.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
  Projects/Modules/LogManager/Sources/CommonAnalyticsLog.swift
Labels: 3️⃣ Priority: Low

#1181 🔀 :: (#1180) 리스트 검색결과 단위 회 -> 구독 변경
  Projects/Features/SearchFeature/Sources/After/View/ListResultCell.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+Int.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#1183 🔀 :: (#1118) 정렬 옵션 변경 , 가나다순 -> 관련도순
  Projects/Domains/SearchDomain/Interface/Enum/Option.swift
  Projects/Features/SearchFeature/Sources/After/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SearchSortOptionViewController.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#1187 🔀 :: (#1146) 홈 탭 광클시 크래쉬 현상 수정
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
Labels: 🐞 Bug, 2️⃣ Priority: Medium

#1188 🔀 :: (#1186) 재생목록화면 재생버튼 UI 변경
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/Views/RandomPlayButtonHeaderView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#1184 🔀 :: (#1167) Firebase Send Error
  Projects/Modules/LogManager/Sources/AnalyticsLogManager.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+PreferenceManager.swift
Labels: 🌏 Deploy, 2️⃣ Priority: Medium, ⚙ Setting

#1194 🔀 :: (#1193) 플리 이미지 변경 시 로딩 인디케이터 센터 정렬
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/UsertInterfaces/DesignSystem/Sources/WMNavigationBarView.swift
Labels: 3️⃣ Priority: Low

#1192 🔀 :: (#1189) 누락 로그 및 수정,추가된 로그 작업
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/Features/ArtistFeature/Sources/Analytics/ArtistAnalyticsLog.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistDetailViewModel.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
  Projects/Features/BaseFeature/Sources/Analytics/ContainSongsAnalyticsLog.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/MainTabFeature/Sources/Analytics/NoticePopupAnalyticsLog.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/NoticePopupViewController.swift
  Projects/Features/MusicDetailFeature/Sources/Analytics/MusicDetailAnalyticsLog.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
  Projects/Features/MyInfoFeature/Sources/Analytics/FAQAnalyticsLog.swift
  Projects/Features/MyInfoFeature/Sources/Analytics/InquiryAnalyticsLog.swift
  Projects/Features/MyInfoFeature/Sources/Analytics/MyInfoAnalyticsLog.swift
  Projects/Features/MyInfoFeature/Sources/Analytics/NoticeAnalyticsLog.swift
  Projects/Features/MyInfoFeature/Sources/Analytics/SettingAnalyticsLog.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/FAQ/FaqContentViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/FAQ/FaqViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Notice/NoticeViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Question/QuestionViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/FaqViewModel.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/OpenSourceLicenseViewModel.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewModels/PlayListViewModel.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/Root/ViewControllers/SearchViewController.swift
  Projects/Features/SignInFeature/Sources/Analytics/SigninAnalyticsLog.swift
  Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/StorageReactor.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
  Projects/Modules/LogManager/Sources/AnalyticsLogManager.swift
  Projects/Modules/LogManager/Sources/AnalyticsUserProperty.swift
  Projects/Modules/LogManager/Sources/CommonAnalyticsLog.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+PreferenceManager.swift
Labels: 0️⃣ Priority: Critical, 🌏 Deploy, ✨ Feature

#1195 🔀 :: (#1185) 이름 제한 12자 + 영문자는 2글자당 1문자로 판정
  Projects/Features/BaseFeature/Interface/Enum/PurposeType.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
Labels: 1️⃣ Priority: High, ⚡️ Performance, ✨ Feature

#1201 🔀 :: (#1199) 보관함 > 내 플리 상세 진입 시 플로팅 버튼 위치 안맞는 UI 오류 수정
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
  Projects/Modules/Utility/Sources/Enums/PlaylistFloatingButtonPosition.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+Notification.Name.swift
Labels: 0️⃣ Priority: Critical

#1209 🔀 :: (#1207) Wm 네이밍 -> WM로 변경
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/Domains/PlaylistDomain/Interface/DataSource/RemotePlaylistDataSource.swift
  Projects/Domains/PlaylistDomain/Interface/Entity/WMPlaylistDetailEntity.swift
  Projects/Domains/PlaylistDomain/Interface/Repository/PlaylistRepository.swift
  Projects/Domains/PlaylistDomain/Interface/UseCase/FetchWMPlaylistDetailUseCase.swift
  Projects/Domains/PlaylistDomain/Interface/UseCase/FetchWmPlaylistDetailUseCase.swift
  Projects/Domains/PlaylistDomain/Sources/API/PlaylistAPI.swift
  Projects/Domains/PlaylistDomain/Sources/DataSource/RemotePlaylistDataSourceImpl.swift
  Projects/Domains/PlaylistDomain/Sources/Repository/PlaylistRepositoryImpl.swift
  Projects/Domains/PlaylistDomain/Sources/ResponseDTO/WmPlaylistDetailResponseDTO.swift
  Projects/Domains/PlaylistDomain/Sources/UseCase/FetchWMPlaylistDetailUseCaseImpl.swift
  Projects/Features/PlaylistFeature/Interface/PlaylistDetailNavigator.swift
  Projects/Features/PlaylistFeature/Sources/Components/WakmusicPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/WakmusicPlaylistDetailReactor.swift
  Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
Labels: ⚡️ Simple, 2️⃣ Priority: Medium

#1211 🔀:: (#1204) Credit 작업자 노래 리스트 누락 스펙 반영
  Projects/Features/CreditSongListFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/Component/CreditSongListTabItemComponent.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/View/CreditSongCollectionViewCell.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/View/RandomPlayButton.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#1214 🔀:: (#1210) 가사 하이라이팅 활성화 UI 추가
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController+Bind.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#1217 🔀:: (#1216) 가사 하이라이팅 총 라인 계산 기준 수정
  Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
Labels: ⚡️ Performance

#1219 🔀 :: (#1218) Issue Auto Closer trigger가 안되는 현상 해결
  .github/actions/Auto_close_associate_issue/main.js
  .github/workflows/AutoCloseIssueByPullRequest.yml
Labels: 3️⃣ Priority: Low, ⚙ Setting

#1222 🔀 :: (#1221) 구독 버튼 보여지는 시기 변경
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#1226 🔀 :: (#1225) 아티스트 숏네임 사용 오류 수정
  Projects/Domains/ArtistDomain/Sources/ResponseDTO/ArtistDetailResponseDTO.swift
  Projects/Domains/ArtistDomain/Sources/ResponseDTO/ArtistListResponseDTO.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1224 🔀 :: (#1223) 작업자 이름이 길어질 때를 위한 최대 width
  Projects/Features/SongCreditFeature/Sources/View/CreditCollectionView/CreditCollectionViewCell.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1228 🔀 :: (#1227) 노래 상세에 진입 시 진입점 구분 없이 노래 상세의 데이터를 사용하도록 변경
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#1229 🔀 :: (#1220) 플리 보관함에 잠금 유무 표시
  Projects/Domains/UserDomain/Interface/Entity/PlaylistEntity.swift
  Projects/Domains/UserDomain/Sources/ResponseDTO/PlaylistResponseDTO.swift
  Projects/Domains/UserDomain/Testing/FetchPlaylistUseCaseStub.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/StorageFeature/Sources/Views/ListStorageTableViewCell.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Storage.xcassets/storage_close.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Storage.xcassets/storage_close.imageset/ic_16_close@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Storage.xcassets/storage_close.imageset/ic_16_close@3x.png
Labels: 1️⃣ Priority: High, ⚡️ Simple

#1232 🔀 :: (#1206) 재생 타입(유튜브, 유튜브 뮤직) 선택 팝업 뷰 구현
  Projects/App/Sources/Application/AppComponent+MyInfo.swift
  Projects/App/Support/Info.plist
  Projects/Features/MyInfoFeature/Interface/Enum/SettingItemCategory.swift
  Projects/Features/MyInfoFeature/Interface/Protocol/PlayTypeTogglePopupFactory.swift
  Projects/Features/MyInfoFeature/Sources/Components/PlayTypeTogglePopupComponent.swift
  Projects/Features/MyInfoFeature/Sources/Components/SettingComponent.swift
  Projects/Features/MyInfoFeature/Sources/DataSource/SettingItemDataSource.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/SettingReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/PlayTypeTogglePopup/PlayTypeTogglePopupViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/PlayTypeTogglePopupItemButton.swift
  Projects/Features/MyInfoFeature/Sources/Views/SettingItemTableViewCell.swift
  Projects/Features/MyInfoFeature/Testing/SettingComponentStub.swift
  Projects/Modules/Utility/Sources/Enums/YoutubePlayType.swift
  Projects/Modules/Utility/Sources/Manager/PreferenceManager.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MyInfo.xcassets/donut.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MyInfo.xcassets/donut.imageset/radio_button@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MyInfo.xcassets/donut.imageset/radio_button@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MyInfo.xcassets/donut_color.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MyInfo.xcassets/donut_color.imageset/radio_button_fill@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MyInfo.xcassets/donut_color.imageset/radio_button_fill@3x.png
  Projects/UsertInterfaces/DesignSystem/Sources/Extension+UILabel.swift
  Projects/UsertInterfaces/DesignSystem/Sources/WMLabel.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#1235 🔀 :: (#1213) multiPurposePopUp -> multiPurposePopup 리네이밍
  Projects/App/Sources/Application/AppComponent+Base.swift
  Projects/Features/BaseFeature/Interface/MultiPurposePopup/MultiPurposePopupFactory.swift
  Projects/Features/BaseFeature/Sources/Components/ContainSongsComponent.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
  Projects/Features/MyInfoFeature/Sources/Components/MyInfoComponent.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
  Projects/Features/StorageFeature/Sources/Components/ListStorageComponent.swift
  Projects/Features/StorageFeature/Sources/Components/StorageComponent.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
Labels: 3️⃣ Priority: Low

#1233 🔀 :: (#1231) 크레딧 작업자 노래 리스트에서 썸네일 클릭 시 재생목록의 첫 곡으로 이동되는 이슈 해결
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
  Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewModels/MainTabBarViewModel.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailView.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/ThumbnailCollectionView/ThumbnailCell.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1236 🔀 :: (#1200) 재생 플랫폼에 유튜브 뮤직 지원
  Projects/Modules/Utility/Sources/Player/WakmusicYoutubePlayer.swift
  Projects/Modules/Utility/Sources/Youtube/YoutubeURLGenerator.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#1239 🔀 :: (#1237) 신규 로그 추가
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/Features/MyInfoFeature/Sources/Analytics/SettingAnalyticsLog.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/SettingReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/PlayTypeTogglePopup/PlayTypeTogglePopupViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/SettingItemTableViewCell.swift
  Projects/Modules/LogManager/Sources/AnalyticsUserProperty.swift
  Projects/Modules/Utility/Sources/Manager/PreferenceManager.swift
  Projects/Modules/Utility/Sources/Player/WakmusicYoutubePlayer.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#1240 🔀 :: (#1238) 음악 재생 타입 팝업 Animation Spec 변경
  Projects/Features/MyInfoFeature/Sources/ViewControllers/PlayTypeTogglePopup/PlayTypeTogglePopupViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#1246 🔀 :: (#1245) SingleAction 버튼 Blur 적용
  Projects/UsertInterfaces/DesignSystem/Sources/SingleActionButtonView.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#1249 🔀 :: (#1248) 단일곡 재생 시 제목에 Shorts를 의미하는 텍스트가 포함되어있을 시Youtube로 재생
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/Views/PlaylistTableViewCell.swift
  Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+String.swift
  Projects/Modules/Utility/Sources/Player/WakmusicYoutubePlayer.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#1250 🔀 :: (#1230) 노래 상세에서 재생목록 접근 시 재생목록 자동 스크롤
  Projects/Features/BaseFeature/Sources/GlobalState/PlayListPresenterGlobalState.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
  Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
  Projects/Features/PlaylistFeature/Interface/PlaylistFactory.swift
  Projects/Features/PlaylistFeature/Sources/Components/PlaylistComponent.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
Labels: ✨ Feature, 2️⃣ Priority: Medium

#1255 🔀 :: (#1252) 곡 담기 blur 처리
  Projects/Features/BaseFeature/Resources/Base.storyboard
  Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
  Projects/Features/BaseFeature/Sources/Views/ContainPlaylistHeaderView.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewModels/PlaylistViewModel.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#1256 🔀 :: (#1244) PDF 로드 실패 처리
  Projects/Features/BaseFeature/Sources/ViewControllers/ContractViewController.swift
Labels: ⚡️ Simple, 3️⃣ Priority: Low

#1260 🔀 :: (#1259) 아티스트 설명글 짤림 보완
  Projects/Features/ArtistFeature/Resources/Artist.storyboard
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extension+UILabel.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1261 🔀 :: (#1208) deprecated 토스트 함수 제거
  Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
Labels: 3️⃣ Priority: Low

#1266 🔀 :: (#1264) 푸시발송 이스터에그 제거
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/Features/ArtistFeature/Resources/Artist.storyboard
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Labels: 0️⃣ Priority: Critical

#1265 🔀 :: (#1263) 딥링크 도메인 분기처리
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/Modules/Utility/Sources/DeepLink/DeepLinkGenerator.swift
  Projects/Modules/Utility/Sources/Utils/Secrets.swift
Labels: 0️⃣ Priority: Critical

#1271 🔀 :: (#1257) 플레이리스트 상세 글자 넘침 버그 해결
  Projects/Features/PlaylistFeature/Sources/Views/MyPlaylistHeaderView.swift
  Projects/Features/PlaylistFeature/Sources/Views/UnknownPlaylistHeaderView.swift
  Projects/Features/PlaylistFeature/Sources/Views/WakmusicPlaylistHeaderView.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#1267 🔀 :: (#1243) fix 미설치 버튼 터치 영역 확장
  Projects/Features/MyInfoFeature/Sources/Views/PlayTypeTogglePopupItemButton.swift
Labels: ✨ Feature, 3️⃣ Priority: Low

#1272 🔀 :: (#1268) 재생 방식 토글 버튼 UI 수정
  Projects/Features/MyInfoFeature/Sources/ViewControllers/PlayTypeTogglePopup/PlayTypeTogglePopupViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/PlayTypeTogglePopupItemButton.swift
Labels: 1️⃣ Priority: High

#1273 🔀 :: (#1262) 보관함 리스트 만들기 버튼 UI 수정
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
  Projects/Features/StorageFeature/Sources/Views/CreateListButton.swift
  Projects/Features/StorageFeature/Sources/Views/ListStorageView.swift
Labels: 1️⃣ Priority: High

#1270 🔀 :: (#1269) WMImageAPI 미사용 코드 제거
  Projects/Modules/Utility/Sources/API/WMImageAPI.swift
Labels: 1️⃣ Priority: High
