Repository wakmusic/wakmusic-iOS, pull requests merged in 2024-02, with the labels that each got.

#405 🔀 :: (#403) SwiftLint workflow가 항상 실패하는 현상 해결
  .github/workflows/SwiftLint.yml
  .swiftlint.yml
Labels: bug

#404 🔀 :: (#401) CI 환경 개선
  .github/workflows/CI.yml
  .github/workflows/CachingDependencies.yml
  .gitignore
  Makefile
  Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+Carthage.swift
  Projects/Features/CommonFeature/Sources/PlayState/PlayState.swift
  Projects/Features/CommonFeature/Tests/TargetTests.swift
  Projects/Modules/FeatureThirdPartyLib/Project.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Projects/Modules/ThirdPartyLib/Tests/TargetTests.swift
  Projects/Modules/Utility/Tests/TargetTests.swift
  Projects/UsertInterfaces/DesignSystem/Project.swift
  Tuist/Dependencies.swift
  Tuist/Package.resolved
  Tuist/Package.swift
Labels: enhancement

#409 🔀 :: (#408) 인원 변동으로 인한 CODEOWNER 수정
  .github/CODEOWNERS
Labels: documentation

#412 🔀 :: (#410) PR 템플릿
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#418 🔀 :: (#416) 플러그인을 이용한
  Makefile
  Plugin/DependencyPlugin/Plugin.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Carthage.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+Project.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/PathExtension.swift
  Plugin/EnvironmentPlugin/Plugin.swift
  Plugin/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Plugin/UtilityPlugin/Plugin.swift
  Plugin/UtilityPlugin/ProjectDescriptionHelpers/Dependency+XCFramework‎.swift
  Projects/App/Project.swift
  Projects/Modules/FeatureThirdPartyLib/Project.swift
  Projects/Modules/ThirdPartyLib/Project.swift
  Scripts/generatePlugin.swift
  Tuist/Config.swift
  Tuist/ProjectDescriptionHelpers/Environment.swift
  Tuist/ProjectDescriptionHelpers/Project+Template.swift
  Tuist/ProjectDescriptionHelpers/Workspace+Scheme.swift
  Workspace.swift
Labels: ♻️ Refactor, ⚙ Setting

#422 🔀 :: (#419) MFA 도입을 위한 sugar 코드 도입
  Makefile
  Plugin/ConfigurationPlugin/Plugin.swift
  Plugin/ConfigurationPlugin/ProjectDescriptionHelpers/Configuration+Ext.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/PathExtension.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/TargetDependency+MicroFeatureTarget.swift
  Plugin/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Projects/App/Project.swift
  Projects/Features/StorageFeature/Project.swift
  Scripts/generatePlugin.swift
  Tuist/Config.swift
  Tuist/ProjectDescriptionHelpers/GenerateEnvironment.swift
  Tuist/ProjectDescriptionHelpers/Internal/Configurable.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+Template.swift
  Tuist/ProjectDescriptionHelpers/SourceFiles+Template.swift
  Tuist/ProjectDescriptionHelpers/SourceFiles/SourceFiles+Template.swift
  Tuist/ProjectDescriptionHelpers/Target/Target+MicroFeatures.swift
  Tuist/ProjectDescriptionHelpers/Target/TargetSpec.swift
  graph.png
Labels: ♻️ Refactor, ⚙ Setting
