Repository wakmusic/wakmusic-iOS, pull requests merged in 2024-09, with the labels that each got.

#1276 🔀 :: (#1275) 재생목록 > 랜덤 아이콘 크기 변경
  Projects/Features/PlaylistFeature/Sources/Views/RandomPlayButtonGroupView.swift
  Projects/Features/PlaylistFeature/Sources/Views/RandomPlayButtonHeaderView.swift
Labels: 1️⃣ Priority: High

#1274 🔀 :: (#1258) 닉네임 입력 조건 추가
  Projects/Features/BaseFeature/Resources/Base.storyboard
  Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1281 🔀 :: (#1279) Release 타겟 빌드 에러 수정
  Projects/Domains/BaseDomain/Sources/DataSource/BaseRemoteDataSource.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#1278 🔀 :: (#1277) 미사용 화면 제거 (RequestVC)
  Projects/Features/MyInfoFeature/Resources/Request.storyboard
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Request/RequestViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/RequestViewModel.swift
Labels: 3️⃣ Priority: Low

#1282 🔀 :: (#974) (보관함 > 내 리스트) 애니메이션 초기화 과정 안보이게 수정
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
  Projects/Features/StorageFeature/Sources/Views/ListStorageView.swift
  Projects/Features/StorageFeature/Sources/Views/ParticleAnimationView.swift
Labels: ✨ Feature, 🐞 Bug, 3️⃣ Priority: Low

#1284 🔀 :: (#1283) 쇼츠로만 구성하여 재생 시 항상 유튜브로만 재생
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
Labels: ✨ Feature, 3️⃣ Priority: Low

#1286 🔀 :: (#1285) 참여정보(크레딧) > 데이터 없을 때 UI 처리
  Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
Labels: 0️⃣ Priority: Critical

#1288 🔀 :: (#1287) privacy, terms 주소 변경
  Projects/App/Support/Info.plist
  Projects/Features/BaseFeature/Sources/ViewControllers/ContractViewController.swift
  Projects/Modules/Utility/Sources/Utils/Secrets.swift
Labels: 1️⃣ Priority: High

#1292 🔀 :: (#1291) 아티스트 소개글 터치영역 변경
  Projects/Features/ArtistFeature/Resources/Artist.storyboard
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
Labels: 0️⃣ Priority: Critical

#1290 🔀 :: (#1289) 누락된 열매함 바로가기 기능 추가
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/FruitDrawButtonView.swift
  Projects/Features/MyInfoFeature/Sources/Views/MyInfoView.swift
Labels: ✨ Feature, 3️⃣ Priority: Low

#1294 🔀 :: (#1293) 중복 닉네임 에러 캐치 등
  Projects/Domains/UserDomain/Sources/API/UserAPI.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
Labels: 1️⃣ Priority: High

#1298 🔀 :: (#1297) 애널리틱스 로그 누락
  Projects/Modules/LogManager/Sources/AnalyticsLogManager.swift
Labels: 1️⃣ Priority: High

#1300 🔀 :: (#1296) 플레이리스트의 중복곡 처리
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlaylistItem.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+Sequence.swift
  Projects/Modules/Utility/Sources/Utils/UniquedSequence.swift
Labels: 🐞 Bug

#1301 🔀 :: (#1296) 중복된 곡을 삭제할 때 Crash나는 이슈 해결
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
Labels: 🐞 Bug

#1302 🔀 :: (#1299) 빈토큰 미전송
  Projects/Domains/BaseDomain/Sources/BasePlugin/BasePlugin.swift
Labels: 🐞 Bug
