Repository wakmusic/wakmusic-iOS, pull requests merged in 2024-03, with the labels that each got.

#426 🔀 :: (#424) MicroFeatures Scaffold 추가
  Plugin/TemplatePlugin/Plugin.swift
  Plugin/TemplatePlugin/Templates/Demo/Demo.swift
  Plugin/TemplatePlugin/Templates/Demo/DemoResources.stencil
  Plugin/TemplatePlugin/Templates/Demo/DemoSources.stencil
  Plugin/TemplatePlugin/Templates/Interface/Interface.stencil
  Plugin/TemplatePlugin/Templates/Interface/Interface.swift
  Plugin/TemplatePlugin/Templates/Sources/Sources.stencil
  Plugin/TemplatePlugin/Templates/Sources/Sources.swift
  Plugin/TemplatePlugin/Templates/Testing/Testing.stencil
  Plugin/TemplatePlugin/Templates/Testing/Testing.swift
  Plugin/TemplatePlugin/Templates/Tests/Tests.stencil
  Plugin/TemplatePlugin/Templates/Tests/Tests.swift
  Plugin/TemplatePlugin/Templates/UITests/UITests.stencil
  Plugin/TemplatePlugin/Templates/UITests/UITests.swift
  Tuist/Config.swift
Labels: ⚙ Setting

#427 🔀 :: (#424) 모듈 생성 스크립트 최신 코드 동기화
  Makefile
  Scripts/GenerateModule.swift
Labels: ⚙ Setting

#444 🔀 :: (#443) 모듈 생성 스크립트 예외처리
  Scripts/GenerateModule.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#445 🔀 :: (#411) 개발 환경 세팅 스크립트화
  .gitconfig
  .githooks/.gitkeep
  Makefile
  Scripts/Setup.sh
Labels: ⚙ Setting

#448 🔀 :: (#446) SwiftLint config파일 단 하나의 파일로 사용하도록 변경
  .swiftlint.yml
  Projects/App/.swiftlint.yml
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/ArtistFeature/.swiftlint.yml
  Projects/Features/BaseFeature/.swiftlint.yml
  Projects/Features/ChartFeature/.swiftlint.yml
  Projects/Features/CommonFeature/.swiftlint.yml
  Projects/Features/HomeFeature/.swiftlint.yml
  Projects/Features/MainTabFeature/.swiftlint.yml
  Projects/Features/PlayerFeature/.swiftlint.yml
  Projects/Features/RootFeature/.swiftlint.yml
  Projects/Features/SearchFeature/.swiftlint.yml
  Projects/Features/SignInFeature/.swiftlint.yml
  Projects/Features/StorageFeature/.swiftlint.yml
  Projects/Modules/FeatureThirdPartyLib/.swiftlint.yml
  Projects/Modules/ThirdPartyLib/.swiftlint.yml
  Projects/Modules/Utility/.swiftlint.yml
  Projects/Services/APIKit/.swiftlint.yml
  Projects/Services/DataMappingModule/.swiftlint.yml
  Projects/Services/DataModule/.swiftlint.yml
  Projects/Services/DatabaseModule/.swiftlint.yml
  Projects/Services/DomainModule/.swiftlint.yml
  Projects/Services/NetworkModule/.swiftlint.yml
  Projects/UsertInterfaces/DesignSystem/.swiftlint.yml
  Scripts/SwiftLintRunScript.sh
Labels: ⚙ Setting

#450 🔀 :: (#417) SwiftLint와 SwiftFormat 설정
  .githooks/.gitkeep
  .githooks/pre-commit
  .swiftformat
  .swiftlint.yml
  Makefile
Labels: ⚙ Setting

#449 🔀 :: (#433) PR Assign, Labels 지정 자동화 workflow 추가
  .github/workflows/AutoAssign.yml
  .github/workflows/IssueToPRLabelSync.yml
  .github/workflows/IssueToPRLabelSync/ExtractIssueNumber.sh
Labels: ⚙ Setting

#452 🔀 :: (#435) 도메인 모듈 분리 3차
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Auth.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domains/AppDomain/Sources/API/AppAPI.swift
  Projects/Domains/ArtistDomain/Sources/API/ArtistAPI.swift
  Projects/Domains/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domains/AuthDomain/Interface/Entity/AuthLoginEntity.swift
  Projects/Domains/AuthDomain/Interface/Entity/NaverUserInfoEntity.swift
  Projects/Domains/AuthDomain/Interface/Enum/ProviderType.swift
  Projects/Domains/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domains/AuthDomain/Interface/UseCase/FetchNaverUserInfoUseCase.swift
  Projects/Domains/AuthDomain/Interface/UseCase/FetchTokenUseCase.swift
  Projects/Domains/AuthDomain/Project.swift
  Projects/Domains/AuthDomain/Sources/API/AuthAPI.swift
  Projects/Domains/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domains/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domains/AuthDomain/Sources/ResponseDTO/AuthLoginResponseDTO.swift
  Projects/Domains/AuthDomain/Sources/ResponseDTO/NaverUserInfoResponseDTO.swift
  Projects/Domains/AuthDomain/Sources/UseCase/FetchNaverUserInfoUseCaseImpl.swift
  Projects/Domains/AuthDomain/Sources/UseCase/FetchTokenUseCaseImpl.swift
  Projects/Domains/AuthDomain/Tests/AuthDomainTest.swift
  Projects/Features/SignInFeature/Project.swift
  Projects/Features/SignInFeature/Sources/Components/SignInComponent.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
  Projects/Services/NetworkModule/Sources/Auth/DataTransfer/FetchNaverUserInfoTransfer.swift
  Projects/Services/NetworkModule/Sources/Auth/DataTransfer/FetchTokenTransfer.swift
  graph.png
Labels: ⚡️ Performance, ♻️ Refactor

#454 🔀 :: (#453) 의존성 캐시의 flag인 hashFile의 입력 파일 변경
  .github/workflows/CI.yml
Labels: ⚡️ Simple, ⚙ Setting

#460 🔀 :: (#436) 도메인 모듈 분리 4차
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Chart.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domains/ChartDomain/Interface/DataSource/RemoteChartDataSource.swift
  Projects/Domains/ChartDomain/Interface/Entity/ChartRankingEntity.swift
  Projects/Domains/ChartDomain/Interface/Enum/ChartDateType.swift
  Projects/Domains/ChartDomain/Interface/Repository/ChartRepository.swift
  Projects/Domains/ChartDomain/Interface/UseCase/FetchChartRankingUseCase.swift
  Projects/Domains/ChartDomain/Interface/UseCase/FetchChartUpdateTimeUseCase.swift
  Projects/Domains/ChartDomain/Project.swift
  Projects/Domains/ChartDomain/Sources/API/ChartAPI.swift
  Projects/Domains/ChartDomain/Sources/DataSource/RemoteChartDataSourceImpl.swift
  Projects/Domains/ChartDomain/Sources/Repository/ChartRepositoryImpl.swift
  Projects/Domains/ChartDomain/Sources/ResponseDTO/FetchChartRankingResponseDTO.swift
  Projects/Domains/ChartDomain/Sources/UseCase/FetchChartRankingUseCaseImpl.swift
  Projects/Domains/ChartDomain/Sources/UseCase/FetchChartUpdateTimeUseCaseImpl.swift
  Projects/Domains/ChartDomain/Tests/ChartDomainTest.swift
  Projects/Features/ChartFeature/Project.swift
  Projects/Features/ChartFeature/Sources/Components/ChartContentComponent.swift
  Projects/Features/ChartFeature/Sources/ViewModels/ChartContentViewModel.swift
  Projects/Features/ChartFeature/Sources/Views/ChartContentTableViewCell.swift
  Projects/Features/CommonFeature/Sources/Components/NewSongsContentComponent.swift
  Projects/Features/CommonFeature/Sources/ViewModels/NewSongsContentViewModel.swift
  Projects/Features/HomeFeature/Project.swift
  Projects/Features/HomeFeature/Sources/Components/HomeComponent.swift
  Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
  Projects/Features/HomeFeature/Sources/Views/HomeChartCell.swift
  Projects/Services/DataMappingModule/Sources/Base/AppInfoFlagType.swift
  Projects/Services/DataMappingModule/Sources/Chart/Response/FetchChartRankingResponseDTO.swift
  graph.png
Labels: ⚡️ Performance, 2️⃣ Priority: Medium, ♻️ Refactor

#464 🔀 :: (#437) 도메인 모듈 분리 5차
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Faq.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domains/ChartDomain/Sources/Repository/ChartRepositoryImpl.swift
  Projects/Domains/FaqDomain/Interface/DataSource/RemoteFaqDataSource.swift
  Projects/Domains/FaqDomain/Interface/Entity/FaqCategoryEntity.swift
  Projects/Domains/FaqDomain/Interface/Entity/FaqEntity.swift
  Projects/Domains/FaqDomain/Interface/Repository/FaqRepository.swift
  Projects/Domains/FaqDomain/Interface/UseCase/FetchFaqCategoriesUseCase.swift
  Projects/Domains/FaqDomain/Interface/UseCase/FetchFaqUseCase.swift
  Projects/Domains/FaqDomain/Project.swift
  Projects/Domains/FaqDomain/Sources/API/FaqAPI.swift
  Projects/Domains/FaqDomain/Sources/DataSource/RemoteFaqDataSourceImpl.swift
  Projects/Domains/FaqDomain/Sources/Repository/FaqRepositoryImpl.swift
  Projects/Domains/FaqDomain/Sources/ResponseDTO/FaqCategoryResponseDTO.swift
  Projects/Domains/FaqDomain/Sources/ResponseDTO/FaqResponseDTO.swift
  Projects/Domains/FaqDomain/Sources/UseCase/FetchFaqCategoriesUseCaseImpl.swift
  Projects/Domains/FaqDomain/Sources/UseCase/FetchFaqUseCaseImpl.swift
  Projects/Domains/FaqDomain/Tests/FaqDomainTest.swift
  Projects/Features/StorageFeature/Project.swift
  Projects/Features/StorageFeature/Sources/Components/FaqComponent.swift
  Projects/Features/StorageFeature/Sources/Components/FaqContentComponent.swift
  Projects/Features/StorageFeature/Sources/ViewModels/FaqViewModel.swift
  Projects/Features/StorageFeature/Sources/ViewModels/QnaContentViewModel.swift
  Projects/Features/StorageFeature/Sources/Views/AnswerTableViewCell.swift
  Projects/Features/StorageFeature/Sources/Views/QuestionTableViewCell.swift
  Projects/Services/DataMappingModule/Sources/Faq/Response/FaqCategoryResponseDTO.swift
  Projects/Services/NetworkModule/Sources/Faq/DataTransfer/FetchQnaTransfer.swift
  graph.png
Labels: ⚡️ Performance, 2️⃣ Priority: Medium, ♻️ Refactor

#467 🔀 :: (#438) 도메인 모듈 분리 6차
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Like.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domains/LikeDomain/Interface/DataSource/RemoteLikeDataSource.swift
  Projects/Domains/LikeDomain/Interface/Entity/LikeEntity.swift
  Projects/Domains/LikeDomain/Interface/Repository/LikeRepository.swift
  Projects/Domains/LikeDomain/Interface/UseCase/AddLikeSongUseCase.swift
  Projects/Domains/LikeDomain/Interface/UseCase/CancelLikeSongUseCase.swift
  Projects/Domains/LikeDomain/Interface/UseCase/FetchLikeNumOfSongUseCase.swift
  Projects/Domains/LikeDomain/Project.swift
  Projects/Domains/LikeDomain/Sources/API/LikeAPI.swift
  Projects/Domains/LikeDomain/Sources/DataSource/RemoteLikeDataSourceImpl.swift
  Projects/Domains/LikeDomain/Sources/Repository/LikeRepositoryImpl.swift
  Projects/Domains/LikeDomain/Sources/ResponseDTO/FetchLikeResponseDTO.swift
  Projects/Domains/LikeDomain/Sources/ResponseDTO/LikeResponseDTO.swift
  Projects/Domains/LikeDomain/Sources/UseCase/AddLikeSongUseCaseImpl.swift
  Projects/Domains/LikeDomain/Sources/UseCase/CancelLikeSongUseCaseImpl.swift
  Projects/Domains/LikeDomain/Sources/UseCase/FetchLikeNumOfSongUseCaseImpl.swift
  Projects/Domains/LikeDomain/Tests/LikeDomainTest.swift
  Projects/Features/PlayerFeature/Project.swift
  Projects/Features/PlayerFeature/Sources/Components/PlayerComponent.swift
  Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel+API.swift
  Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
  Projects/Services/DataMappingModule/Sources/Like/Response/LikeResponseDTO.swift
  graph.png
Labels: ⚡️ Performance, 2️⃣ Priority: Medium, ♻️ Refactor

#468 🔀 :: (#439) 도메인 모듈 분리 7차
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Notice.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domains/NoticeDomain/Interface/DataSource/RemoteNoticeDataSource.swift
  Projects/Domains/NoticeDomain/Interface/Entity/FetchNoticeCategoriesEntity.swift
  Projects/Domains/NoticeDomain/Interface/Entity/FetchNoticeEntity.swift
  Projects/Domains/NoticeDomain/Interface/Enum/NoticeType.swift
  Projects/Domains/NoticeDomain/Interface/Repository/NoticeRepository.swift
  Projects/Domains/NoticeDomain/Interface/UseCase/FetchNoticeCategoriesUseCase.swift
  Projects/Domains/NoticeDomain/Interface/UseCase/FetchNoticeUseCase.swift
  Projects/Domains/NoticeDomain/Project.swift
  Projects/Domains/NoticeDomain/Sources/API/NoticeAPI.swift
  Projects/Domains/NoticeDomain/Sources/DataSource/RemoteNoticeDataSourceImpl.swift
  Projects/Domains/NoticeDomain/Sources/Repository/NoticeRepositoryImpl.swift
  Projects/Domains/NoticeDomain/Sources/ResponseDTO/FetchNoticeCategoriesResponseDTO.swift
  Projects/Domains/NoticeDomain/Sources/ResponseDTO/FetchNoticeResponseDTO.swift
  Projects/Domains/NoticeDomain/Sources/UseCase/FetchNoticeCategoriesUseCaseImpl.swift
  Projects/Domains/NoticeDomain/Sources/UseCase/FetchNoticeUseCaseImpl.swift
  Projects/Domains/NoticeDomain/Tests/NoticeDomainTest.swift
  Projects/Features/CommonFeature/Sources/Components/NoticePopupComponent.swift
  Projects/Features/CommonFeature/Sources/ViewControllers/NoticePopupViewController.swift
  Projects/Features/CommonFeature/Sources/ViewModels/NoticePopupViewModel.swift
  Projects/Features/MainTabFeature/Project.swift
  Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewModels/MainTabBarViewModel.swift
  Projects/Features/StorageFeature/Project.swift
  Projects/Features/StorageFeature/Sources/Components/NoticeComponent.swift
  Projects/Features/StorageFeature/Sources/Components/NoticeDetailComponent.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/NoticeDetailViewController.swift
  Projects/Features/StorageFeature/Sources/ViewModels/NoticeDetailViewModel.swift
  Projects/Features/StorageFeature/Sources/ViewModels/NoticeViewModel.swift
  Projects/Features/StorageFeature/Sources/Views/NoticeDetailHeaderView.swift
  Projects/Features/StorageFeature/Sources/Views/NoticeListCell.swift
  Projects/Services/DataMappingModule/Sources/Notice/Response/FetchNoticeCategoriesResponseDTO.swift
  Projects/Services/NetworkModule/Sources/Notice/DataTransfer/FetchNoticeTransfer.swift
  graph.png
Labels: ⚡️ Performance, 2️⃣ Priority: Medium, ♻️ Refactor

#471 🔀 :: (#470) 도메인 모듈 분리 작업 간 누락된 의존성 추가
  Projects/Domains/PlayListDomain/Project.swift
  Projects/Domains/UserDomain/Project.swift
  graph.png
Labels: 🐞 Bug, ♻️ Refactor

#473 🔀 :: (#472) 도메인 모듈 분리 작업 간 누락된 의존성 추가 2t
  Projects/Domains/AppDomain/Project.swift
  Projects/Domains/ArtistDomain/Project.swift
  Projects/Domains/AuthDomain/Project.swift
  Projects/Domains/BaseDomain/Project.swift
  Projects/Domains/ChartDomain/Project.swift
  Projects/Domains/FaqDomain/Project.swift
  Projects/Domains/LikeDomain/Project.swift
  Projects/Domains/NoticeDomain/Project.swift
  Projects/Domains/PlayListDomain/Project.swift
  Projects/Domains/SongsDomain/Project.swift
  Projects/Domains/UserDomain/Project.swift
  graph.png
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#459 🔀 :: (#457) Reactor 의존성 추가
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Features/BaseFeature/Project.swift
  Tuist/Package.resolved
  Tuist/Package.swift
Labels: ⚙ Setting

#456 🔀 :: (#455) make setup 후 tuist command를 못찾는 버그 해결
  Scripts/Setup.sh
Labels: ⚡️ Simple, 🐞 Bug

#462 🔀 :: (#458) Artist화면의 상태관리 객체 viewModel -> Reactor 전환
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/ArtistFeature/Sources/Components/ArtistComponent.swift
  Projects/Features/ArtistFeature/Sources/Reactors/ArtistReactor.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistViewModel.swift
Labels: ♻️ Refactor

#463 🔀 :: (#458) ArtistViewModel 제거
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistViewModel.swift
Labels: ♻️ Refactor

#466 🔀 :: (#458) ArtistReactor Unit Test 작성
  Projects/Domains/ArtistDomain/Project.swift
  Projects/Domains/ArtistDomain/Testing/UseCase/FetchArtistListUseCaseSpy.swift
  Projects/Features/ArtistFeature/Project.swift
  Projects/Features/ArtistFeature/Tests/ArtistReactorTests.swift
  Projects/Features/ArtistFeature/Tests/TargetTests.swift
Labels: ♻️ Refactor, ✅ Test

#475 🔀 :: (#474) SwiftFormat 대상에 NeedleGenerated 파일 제외
  .swiftformat
Labels: ⚡️ Simple, ⚙ Setting
