Repository wakmusic/wakmusic-iOS, pull requests merged in 2024-06, with the labels that each got.

#557 🔀 :: (#556) Home 화면 로그 심기
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/HomeFeature/Sources/Analytics/HomeAnalyticsLog.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetailViewController.swift
  Projects/Modules/LogManager/Sources/CommonAnalyticsLog.swift
Labels: ✨ Feature, 2️⃣ Priority: Medium

#552 🔀 :: (#549) 검색 전 화면을 v3 버전으로 리뉴얼합니다.
  Cartfile.resolved
  Projects/Features/BaseFeature/Resources/RecommendPlayListCell.xib
  Projects/Features/BaseFeature/Sources/ViewControllers/BaseReactorViewController.swift
  Projects/Features/BaseFeature/Sources/Views/RecommendPlayListCell.swift
  Projects/Features/SearchFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Features/SearchFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/SearchFeature/Project.swift
  Projects/Features/SearchFeature/Resources/Search.storyboard
  Projects/Features/SearchFeature/Sources/Components/BeforeSearchComponent.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/BeforeVcDataSoruce.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/Section.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/BeforeSearchCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/Reactors/BeforeSearchReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/SearchReactor.swift
  Projects/Features/SearchFeature/Sources/Service/SearchCommonService.swift
  Projects/Features/SearchFeature/Sources/View/BeforeSearchSectionHeaderView.swift
  Projects/Features/SearchFeature/Sources/View/PopularPlayListCell.swift
  Projects/Features/SearchFeature/Sources/View/RecentRecordTableViewCell.swift
  Projects/Features/SearchFeature/Sources/View/YoutubeThumbnailCell.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SearchViewController.swift
  Projects/Features/SearchFeature/Sources/ViewModels/AfterSearchContentViewModel.swift
  Projects/Features/SearchFeature/Sources/ViewModels/AfterSearchViewModel.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIButton.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Search.xcassets/testThumbnail.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Search.xcassets/testThumbnail.imageset/testThumbnail 1.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Search.xcassets/testThumbnail.imageset/testThumbnail 2.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Search.xcassets/testThumbnail.imageset/testThumbnail.png
Labels: 1️⃣ Priority: High, ✨ Feature

#578 🔀 :: (#577) SignInFeature에 KeyChainModule 의존성을 추가합니다.
  Projects/Features/SignInFeature/Project.swift
Labels: 0️⃣ Priority: Critical

#574 🔀 :: (#561) 왁뮤 추천 플레이리스트 화면을 만들어요.
  Projects/Domains/BaseDomain/Project.swift
  Projects/Domains/PlayListDomain/Interface/DataSource/RemotePlayListDataSource.swift
  Projects/Domains/PlayListDomain/Interface/Entity/AddSongEntity.swift
  Projects/Domains/PlayListDomain/Interface/Entity/RecommendPlayListEntity.swift
  Projects/Domains/PlayListDomain/Interface/Repository/PlayListRepository.swift
  Projects/Domains/PlayListDomain/Interface/UseCase/RemoveSongsUseCase.swift
  Projects/Domains/PlayListDomain/Project.swift
  Projects/Domains/PlayListDomain/Sources/API/PlayListAPI.swift
  Projects/Domains/PlayListDomain/Sources/DataSource/RemotePlayListDataSourceImpl.swift
  Projects/Domains/PlayListDomain/Sources/Repository/PlaylistRepositoryImpl.swift
  Projects/Domains/PlayListDomain/Sources/ResponseDTO/AddSongResponseDTO.swift
  Projects/Domains/PlayListDomain/Sources/UseCase/RemoveSongsUseCaseImpl.swift
  Projects/Domains/PlayListDomain/Testing/FetchPlayListUseCaseStub.swift
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/PlaylistFeature/Sources/PlayListDetailViewModel.swift
  Projects/Features/PlaylistFeature/Testing/PlaylistDetailFactoryStub.swift
  Projects/Features/PlaylistFeature/Testing/Testing.swift
  Projects/Features/SearchFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/SearchFeature/Project.swift
  Projects/Features/SearchFeature/Sources/Components/BeforeSearchComponent.swift
  Projects/Features/SearchFeature/Sources/Components/WakmusicRecommendComponent.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/Section.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/RecommendCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/Reactors/BeforeSearchReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/WakmusicRecommendReactor.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/WakmusicRecommendViewController.swift
  Projects/Features/SearchFeature/Tests/WakmusicRecommendTests.swift
Labels: ✨ Feature

#584 🔀 :: (#550) 설정 네비게이션 버튼 하이라이팅 효과 추가
  Projects/Features/MyInfoFeature/Sources/Views/SettingItemButton.swift
  Projects/Features/MyInfoFeature/Sources/Views/SettingView.swift
Labels: ✨ Feature, ♻️ Refactor, 3️⃣ Priority: Low

#585 🔀 :: (#550) 회원탈퇴 버튼 디자인 및 위치 변경
  Projects/Features/MyInfoFeature/Sources/Views/SettingView.swift
  Projects/Features/MyInfoFeature/Sources/Views/WithDrawLabel.swift
Labels: ⚡️ Simple, ✨ Feature, 3️⃣ Priority: Low

#594 🔀 :: (#550) 내 정보 피쳐의 UILabel을 WMLabel로 대체합니다.
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/FAQ/FaqViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Notice/NoticeDetailViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Notice/NoticeViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/OpenSourceLicense/OpenSourceLicenseViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Question/QuestionViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Request/RequestViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/ServiceInfo/ServiceInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/AppPushSettingView.swift
  Projects/Features/MyInfoFeature/Sources/Views/DrawButtonView.swift
  Projects/Features/MyInfoFeature/Sources/Views/LoginWarningView.swift
  Projects/Features/MyInfoFeature/Sources/Views/NoticeDetailHeaderView.swift
  Projects/Features/MyInfoFeature/Sources/Views/NoticeListCell.swift
  Projects/Features/MyInfoFeature/Sources/Views/OpenSourceLibraryCell.swift
  Projects/Features/MyInfoFeature/Sources/Views/OpenSourceLicenseCell.swift
  Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift
  Projects/Features/MyInfoFeature/Sources/Views/ServiceInfoCell.swift
  Projects/Features/MyInfoFeature/Sources/Views/SettingView.swift
Labels: ⚡️ Simple, ✨ Feature

#582 🔀 :: (#575) 검색 곡 결과 화면 구현
  Projects/App/Sources/Application/AppComponent+Search.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domains/SongsDomain/Interface/Entity/SongEntity.swift
  Projects/Features/SearchFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/SearchFeature/Interface/Enum/TabPosition.swift
  Projects/Features/SearchFeature/Interface/Enum/TypingStatus.swift
  Projects/Features/SearchFeature/Interface/Factory/SearchFactory.swift
  Projects/Features/SearchFeature/Interface/Factory/SearchResultFactory.swift
  Projects/Features/SearchFeature/Resources/Search.storyboard
  Projects/Features/SearchFeature/Sources/Components/AfterSearchComponent.swift
  Projects/Features/SearchFeature/Sources/Components/AfterSearchContentComponent.swift
  Projects/Features/SearchFeature/Sources/Components/SongSearchResultComponent.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/DataSource/BeforeVcDataSoruce.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/Options/Option.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/Section.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/Section/BeforeSearchSection.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/Section/RecommendSection.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/Section/SongSearchResultSection.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/BeforeSearchCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/SongSearchResultCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/Enum/Enum+Search.swift
  Projects/Features/SearchFeature/Sources/Reactors/AfterSearchReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/SearchReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/Service/SearchCommonService.swift
  Projects/Features/SearchFeature/Sources/View/BeforeSearchSectionHeaderView.swift
  Projects/Features/SearchFeature/Sources/View/EntireSectionHeader.swift
  Projects/Features/SearchFeature/Sources/View/OptionButton.swift
  Projects/Features/SearchFeature/Sources/View/RecentRecordHeaderView.swift
  Projects/Features/SearchFeature/Sources/View/SearchResultHeaderView.swift
  Projects/Features/SearchFeature/Sources/View/SongResultCell.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SearchViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewModels/AfterSearchContentViewModel.swift
  Projects/Features/SearchFeature/Sources/ViewModels/AfterSearchViewModel.swift
  Projects/Features/SearchFeature/Sources/ViewModels/BeforeSearchContentViewModel.swift
  Projects/Features/SearchFeature/Sources/ViewModels/SearchViewModel.swift
  Projects/Modules/LogManager/Sources/LogHistory/LogHistoryCell.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Search.xcassets/arrow_down.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Search.xcassets/arrow_down.imageset/ic_16_arrow_down@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Search.xcassets/arrow_down.imageset/ic_16_arrow_down@3x.png
Labels: ✨ Feature

#589 🔀 :: (#588) 검색 퓨처의 UILabel을 WMLabel로 대체합니다.
  Projects/Features/SearchFeature/Sources/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/View/ListResultCell.swift
  Projects/Features/SearchFeature/Sources/View/OptionButton.swift
  Projects/Features/SearchFeature/Sources/View/PopularPlayListCell.swift
  Projects/Features/SearchFeature/Sources/View/RecentRecordHeaderView.swift
  Projects/Features/SearchFeature/Sources/View/RecentRecordTableViewCell.swift
  Projects/Features/SearchFeature/Sources/View/SongResultCell.swift
  Projects/UsertInterfaces/DesignSystem/Sources/WMFontSystem.swift
Labels: ⚡️ Simple, 2️⃣ Priority: Medium

#597 🔀 :: (#596) 공지 화면 리팩토링
  Projects/Features/BaseFeature/Sources/Views/NoticeCollectionViewCell.swift
  Projects/Features/MainTabFeature/Sources/Components/NoticePopupComponent.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/NoticePopupViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewModels/MainTabBarViewModel.swift
  Projects/Features/MainTabFeature/Sources/ViewModels/NoticePopupViewModel.swift
  Projects/Features/StorageFeature/Resources/Storage.storyboard
  Projects/Features/StorageFeature/Sources/ViewControllers/NoticeDetailViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/NoticeViewController.swift
  Projects/Features/StorageFeature/Sources/ViewModels/NoticeDetailViewModel.swift
  Projects/Features/StorageFeature/Sources/ViewModels/NoticeViewModel.swift
Labels: ♻️ Refactor

#608 🔀 :: (#500) AuthDomain api 변경사항 반영
  Projects/App/Sources/Application/AppComponent+Auth.swift
  Projects/Domains/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domains/AuthDomain/Interface/Entity/AuthLoginEntity.swift
  Projects/Domains/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domains/AuthDomain/Interface/UseCase/FetchNaverUserInfoUseCase.swift
  Projects/Domains/AuthDomain/Interface/UseCase/FetchTokenUseCase.swift
  Projects/Domains/AuthDomain/Interface/UseCase/ReGenerateAccessTokenUseCase.swift
  Projects/Domains/AuthDomain/Sources/API/AuthAPI.swift
  Projects/Domains/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domains/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domains/AuthDomain/Sources/ResponseDTO/AuthLoginResponseDTO.swift
  Projects/Domains/AuthDomain/Sources/UseCase/FetchTokenUseCaseImpl.swift
  Projects/Domains/AuthDomain/Sources/UseCase/ReGenerateAccessTokenUseCaseImpl.swift
  Projects/Domains/AuthDomain/Testing/FetchTokenUseCaseSpy.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor

#602 🔀 :: (#510) SearchDomain api 추가 변경사항 반영
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Search.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/App/Support/Info.plist
  Projects/Domains/BaseDomain/Sources/WMAPI/SecretURL.swift
  Projects/Domains/BaseDomain/Sources/WMAPI/WMAPI.swift
  Projects/Domains/SearchDomain/Interface/DataSource/RemoteSearchDataSource.swift
  Projects/Domains/SearchDomain/Interface/Entity/SearchPlaylistEntity.swift
  Projects/Domains/SearchDomain/Interface/Enum/Option.swift
  Projects/Domains/SearchDomain/Interface/Repository/SearchRepository.swift
  Projects/Domains/SearchDomain/Interface/UseCase/FetchSearchPlaylistsUseCase.swift
  Projects/Domains/SearchDomain/Interface/UseCase/FetchSearchSongsUseCase.swift
  Projects/Domains/SearchDomain/Project.swift
  Projects/Domains/SearchDomain/Sources/API/SearchAPI.swift
  Projects/Domains/SearchDomain/Sources/DTO/SearchPlaylistDTO.swift
  Projects/Domains/SearchDomain/Sources/DataSource/RemoteSearchDataSourceImpl.swift
  Projects/Domains/SearchDomain/Sources/Repository/SearchRepositoryImpl.swift
  Projects/Domains/SearchDomain/Sources/UseCase/FetchSearchPlaylistsUseCaseImpl.swift
  Projects/Domains/SearchDomain/Sources/UseCase/FetchSearchSongsUseCaseImpl.swift
  Projects/Features/SearchFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/SearchFeature/Project.swift
  Projects/Features/SearchFeature/Sources/Components/ListSearchResultComponent.swift
  Projects/Features/SearchFeature/Sources/Components/SongSearchResultComponent.swift
  Projects/Features/SearchFeature/Sources/Reactors/ListSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/View/SearchResultHeaderView.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor

#612 🔀 :: (#513) UserDomain api 변경사항 반영
  Projects/Domains/UserDomain/Sources/API/UserAPI.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor

#607 🔀 :: (#603) 검색화면에 Usecase를 연결하여 실제 데이터를 가져옵니다.
  Projects/App/Sources/Application/AppComponent+Search.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domains/SearchDomain/Interface/Entity/SearchPlaylistEntity.swift
  Projects/Domains/SearchDomain/Interface/Enum/Option.swift
  Projects/Domains/SearchDomain/Sources/API/SearchAPI.swift
  Projects/Domains/SearchDomain/Sources/DTO/SearchPlaylistDTO.swift
  Projects/Features/SearchFeature/Sources/Components/ListSearchResultComponent.swift
  Projects/Features/SearchFeature/Sources/Reactors/ListSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/View/ListResultCell.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#610 🔀 :: (#606) 검색 결과화면에 인피니티 스크롤을 구현합니다.
  Projects/Domains/SearchDomain/Sources/DTO/SearchPlaylistDTO.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/ListSearchResultCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/SongSearchResultCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/Reactors/ListSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/View/SearchResultHeaderView.swift
  Projects/Features/SearchFeature/Sources/View/SongResultCell.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SearchViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UICollectionView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Views/LoginWarningView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Views/WMWarningView.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#614 🔀 :: (#566) 보관함의 상단탭을 변경해도 Reactor.State에 반영되지 않던 문제를 수정합니다.
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#613 🔀 :: (#598) AuthDomain api 보완
  Projects/Domains/AuthDomain/Sources/API/AuthAPI.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor

#619 🔀 :: (#568) 내정보 화면을 DemoApp으로 만들기 위한 UseCase Stub 작업
  Projects/Domains/FaqDomain/Project.swift
  Projects/Domains/FaqDomain/Sources/UseCase/FetchFaqCategoriesUseCaseImpl.swift
  Projects/Domains/FaqDomain/Sources/UseCase/FetchFaqUseCaseImpl.swift
  Projects/Domains/FaqDomain/Testing/FetchFaqCategoriesUseCaseStub.swift
  Projects/Domains/FaqDomain/Testing/FetchFaqUseCaseStub.swift
  Projects/Domains/NoticeDomain/Project.swift
  Projects/Domains/NoticeDomain/Sources/UseCase/FetchNoticeCategoriesUseCaseImpl.swift
  Projects/Domains/NoticeDomain/Sources/UseCase/FetchNoticeUseCaseImpl.swift
  Projects/Domains/NoticeDomain/Testing/FetchNoticeCategoriesUseCaseStub.swift
  Projects/Domains/NoticeDomain/Testing/FetchNoticeUseCaseStub.swift
Labels: ♻️ Refactor, 3️⃣ Priority: Low

#621 🔀 :: (#551) PanModal 라이브러리를 FittedSheets로 대체
  Package.resolved
  Package.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Features/BaseFeature/Interface/TextPopUp/TextPopUpFactory.swift
  Projects/Features/BaseFeature/Resources/Base.storyboard
  Projects/Features/BaseFeature/Sources/Components/TextPopUpComponent.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/TextPopupViewController.swift
  Projects/Features/BaseFeature/Sources/Views/SongCartView.swift
  Projects/Features/BaseFeature/Testing/TextPopUpComponentStub.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/MainTabFeature/Resources/Main.storyboard
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/NoticePopupViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Question/QuestionViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Request/RequestViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/ServiceInfo/ServiceInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
  Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
  Projects/Features/PlayerFeature/Sources/ViewControllers/PlaylistViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController+Delegate.swift
  Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SearchViewController.swift
  Projects/Features/StorageFeature/Resources/Storage.storyboard
  Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ProfilePopViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
  Projects/Modules/FeatureThirdPartyLib/Project.swift
  Projects/Modules/Utility/Sources/Enums/BottomSheetSize.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#623 🔀 :: (#618) 검색화면 필터 옵션 모달뷰를 구현했습니다.
  Projects/Domains/SearchDomain/Interface/Enum/Option.swift
  Projects/Features/SearchFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/SearchFeature/Sources/Components/SearchOptionComponent.swift
  Projects/Features/SearchFeature/Sources/View/SearchOptionCell.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SearchOptionViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SearchViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#628 🔀 :: (#622) 정렬 및 필터를 기능을 연결합니다.
  Projects/App/Sources/Application/AppComponent+Search.swift
  Projects/Features/SearchFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/SearchFeature/Resources/Search.storyboard
  Projects/Features/SearchFeature/Sources/Components/ListSearchResultComponent.swift
  Projects/Features/SearchFeature/Sources/Components/SearchOptionComponent.swift
  Projects/Features/SearchFeature/Sources/Components/SearchSortOptionComponent.swift
  Projects/Features/SearchFeature/Sources/Components/SongSearchResultComponent.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/SearchFilterOptionCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/Reactors/ListSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/View/OptionButton.swift
  Projects/Features/SearchFeature/Sources/View/SearchFilterCell.swift
  Projects/Features/SearchFeature/Sources/View/SearchOptionHeaderView.swift
  Projects/Features/SearchFeature/Sources/View/SearchResultHeaderView.swift
  Projects/Features/SearchFeature/Sources/View/SearchSortOptionCell.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/AfterSearchViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SearchSortOptionViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
Labels: 1️⃣ Priority: High, ✨ Feature, ♻️ Refactor

#631 🔀 :: (#629) 검색 전 화면에 실제 데이터를 연결합니다.
  Projects/App/Sources/Application/AppComponent+Chart.swift
  Projects/Domains/ChartDomain/Interface/DataSource/RemoteChartDataSource.swift
  Projects/Domains/ChartDomain/Interface/Entity/CurrentVideoEntity.swift
  Projects/Domains/ChartDomain/Interface/Repository/ChartRepository.swift
  Projects/Domains/ChartDomain/Interface/UseCase/FetchCurrentVideoUseCase.swift
  Projects/Domains/ChartDomain/Sources/API/ChartAPI.swift
  Projects/Domains/ChartDomain/Sources/DataSource/RemoteChartDataSourceImpl.swift
  Projects/Domains/ChartDomain/Sources/Repository/ChartRepositoryImpl.swift
  Projects/Domains/ChartDomain/Sources/ResponseDTO/CurrentVideoDTO.swift
  Projects/Domains/ChartDomain/Sources/UseCase/FetchCurrentVideoUseCaseImpl.swift
  Projects/Domains/PlayListDomain/Interface/Entity/RecommendPlayListEntity.swift
  Projects/Domains/SearchDomain/Sources/DTO/SearchPlaylistDTO.swift
  Projects/Features/SearchFeature/Project.swift
  Projects/Features/SearchFeature/Sources/Components/BeforeSearchComponent.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/DataSource/BeforeVcDataSoruce.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/Section/BeforeSearchSection.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/BeforeSearchCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/Reactors/BeforeSearchReactor.swift
  Projects/Features/SearchFeature/Sources/View/BeforeSearchSectionHeaderView.swift
  Projects/Features/SearchFeature/Sources/View/PopularPlayListCell.swift
  Projects/Features/SearchFeature/Sources/View/YoutubeThumbnailCell.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/WakmusicRecommendViewController.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray800.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Color/BlueGrayColor.xcassets/blueGray900.colorset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Search.xcassets/testThumbnail.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Search.xcassets/testThumbnail.imageset/testThumbnail 1.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Search.xcassets/testThumbnail.imageset/testThumbnail 2.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Search.xcassets/testThumbnail.imageset/testThumbnail.png
  Projects/UsertInterfaces/DesignSystem/Resources/Lottie/Weekly_WM.json
Labels: 1️⃣ Priority: High, ✨ Feature, ♻️ Refactor

#640 🔀 :: (#635) 최신음악 api 변경 대응
  Projects/Domains/SongsDomain/Interface/Entity/NewSongsEntity.swift
  Projects/Domains/SongsDomain/Sources/API/SongsAPI.swift
  Projects/Domains/SongsDomain/Sources/ResponseDTO/NewSongsResponseDTO.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsViewController.swift
  Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
  Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
  Projects/Features/HomeFeature/Sources/Views/HomeChartCell.swift
  Projects/Features/HomeFeature/Sources/Views/HomeNewSongCell.swift
  Projects/Features/HomeFeature/Sources/Views/NewSongsCell.swift
  Projects/Features/MainTabFeature/Sources/Views/PlayListFloatingActionButton.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#639 🔀 :: (#634) 차트 > 홈으로 이동
  Projects/App/Sources/Application/AppComponent+Chart.swift
  Projects/Domains/SongsDomain/Interface/Entity/NewSongsEntity.swift
  Projects/Domains/SongsDomain/Sources/API/SongsAPI.swift
  Projects/Domains/SongsDomain/Sources/ResponseDTO/NewSongsResponseDTO.swift
  Projects/Features/ChartFeature/Interface/ChartFactory.swift
  Projects/Features/ChartFeature/Project.swift
  Projects/Features/ChartFeature/Resources/Chart.storyboard
  Projects/Features/ChartFeature/Sources/Components/ChartComponent.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartViewController.swift
  Projects/Features/ChartFeature/Sources/Views/ChartContentTableViewCell.swift
  Projects/Features/HomeFeature/Project.swift
  Projects/Features/HomeFeature/Sources/Components/HomeComponent.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsViewController.swift
  Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
  Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
  Projects/Features/HomeFeature/Sources/Views/HomeChartCell.swift
  Projects/Features/HomeFeature/Sources/Views/HomeNewSongCell.swift
  Projects/Features/HomeFeature/Sources/Views/NewSongsCell.swift
  Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/BottomTabBarViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/MainTabFeature/Sources/Views/PlayListFloatingActionButton.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/TabBar.xcassets/chart_off.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/TabBar.xcassets/chart_off.imageset/icon_chart_off@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/TabBar.xcassets/chart_off.imageset/icon_chart_off@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/TabBar.xcassets/chart_on.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/TabBar.xcassets/chart_on.imageset/icon_chart_on@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/TabBar.xcassets/chart_on.imageset/icon_chart_on@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Lottie/Chart_Tab.json
  graph.png
Labels: 1️⃣ Priority: High, ⚡️ Simple

#642 🔀 :: (#641) 필터 및 정렬 중복 방지 코드를 적용했습니다.
  Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Performance

#643 🔀 :: (#636) 미사용 UI, 제스쳐 제거
  Projects/Features/MainTabFeature/Resources/Main.storyboard
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#656 🔀 :: (#655) 아티스트 상세 빈 데이터 UI 처리
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#653 🔀 :: (#652) LikeDomain api 변경사항 반영
  Projects/App/Sources/Application/AppComponent+Like.swift
  Projects/Domains/LikeDomain/Interface/DataSource/RemoteLikeDataSource.swift
  Projects/Domains/LikeDomain/Interface/Entity/LikeEntity.swift
  Projects/Domains/LikeDomain/Interface/Repository/LikeRepository.swift
  Projects/Domains/LikeDomain/Interface/UseCase/FetchLikeNumOfSongUseCase.swift
  Projects/Domains/LikeDomain/Sources/API/LikeAPI.swift
  Projects/Domains/LikeDomain/Sources/DataSource/RemoteLikeDataSourceImpl.swift
  Projects/Domains/LikeDomain/Sources/Repository/LikeRepositoryImpl.swift
  Projects/Domains/LikeDomain/Sources/ResponseDTO/FetchLikeResponseDTO.swift
  Projects/Domains/LikeDomain/Sources/ResponseDTO/LikeResponseDTO.swift
  Projects/Domains/LikeDomain/Sources/UseCase/FetchLikeNumOfSongUseCaseImpl.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#651 🔀 :: (#647) 차트 > EqualHandleTappedType 프로토콜 구현 제거
  Projects/App/Sources/Application/AppComponent+Like.swift
  Projects/Domains/LikeDomain/Interface/DataSource/RemoteLikeDataSource.swift
  Projects/Domains/LikeDomain/Interface/Entity/LikeEntity.swift
  Projects/Domains/LikeDomain/Interface/Repository/LikeRepository.swift
  Projects/Domains/LikeDomain/Interface/UseCase/FetchLikeNumOfSongUseCase.swift
  Projects/Domains/LikeDomain/Sources/API/LikeAPI.swift
  Projects/Domains/LikeDomain/Sources/DataSource/RemoteLikeDataSourceImpl.swift
  Projects/Domains/LikeDomain/Sources/Repository/LikeRepositoryImpl.swift
  Projects/Domains/LikeDomain/Sources/ResponseDTO/FetchLikeResponseDTO.swift
  Projects/Domains/LikeDomain/Sources/ResponseDTO/LikeResponseDTO.swift
  Projects/Domains/LikeDomain/Sources/UseCase/FetchLikeNumOfSongUseCaseImpl.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartViewController.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#646 🔀 :: (#645) [Lyric > Image] Domain 변경
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Image.swift
  Projects/App/Sources/Application/AppComponent+Like.swift
  Projects/App/Sources/Application/AppComponent+Lyric.swift
  Projects/App/Support/Info.plist
  Projects/Domains/BaseDomain/Sources/WMAPI/SecretURL.swift
  Projects/Domains/BaseDomain/Sources/WMAPI/WMAPI.swift
  Projects/Domains/ImageDomain/Interface/DataSource/RemoteImageDataSource.swift
  Projects/Domains/ImageDomain/Interface/Entity/LyricDecoratingBackgroundEntity.swift
  Projects/Domains/ImageDomain/Interface/Repository/ImageRepository.swift
  Projects/Domains/ImageDomain/Interface/UseCase/FetchLyricDecoratingBackgroundUseCase.swift
  Projects/Domains/ImageDomain/Project.swift
  Projects/Domains/ImageDomain/Sources/API/ImageAPI.swift
  Projects/Domains/ImageDomain/Sources/DataSource/RemoteImageDataSourceImpl.swift
  Projects/Domains/ImageDomain/Sources/Repository/ImageRepositoryImpl.swift
  Projects/Domains/ImageDomain/Sources/ResponseDTO/LyricDecoratingBackgroundResponseDTO.swift
  Projects/Domains/ImageDomain/Sources/UseCase/FetchLyricDecoratingBackgroundUseCaseImpl.swift
  Projects/Domains/LikeDomain/Interface/DataSource/RemoteLikeDataSource.swift
  Projects/Domains/LikeDomain/Interface/Entity/LikeEntity.swift
  Projects/Domains/LikeDomain/Interface/Repository/LikeRepository.swift
  Projects/Domains/LikeDomain/Interface/UseCase/FetchLikeNumOfSongUseCase.swift
  Projects/Domains/LikeDomain/Sources/API/LikeAPI.swift
  Projects/Domains/LikeDomain/Sources/DataSource/RemoteLikeDataSourceImpl.swift
  Projects/Domains/LikeDomain/Sources/Repository/LikeRepositoryImpl.swift
  Projects/Domains/LikeDomain/Sources/ResponseDTO/FetchLikeResponseDTO.swift
  Projects/Domains/LikeDomain/Sources/ResponseDTO/LikeResponseDTO.swift
  Projects/Domains/LikeDomain/Sources/UseCase/FetchLikeNumOfSongUseCaseImpl.swift
  Projects/Domains/LyricDomain/Interface/DataSource/RemoteLyricDataSource.swift
  Projects/Domains/LyricDomain/Interface/Repository/LyricRepository.swift
  Projects/Domains/LyricDomain/Interface/UseCase/FetchDecoratingBackgroundUseCase.swift
  Projects/Domains/LyricDomain/Sources/DataSource/RemoteLyricDataSourceImpl.swift
  Projects/Domains/LyricDomain/Sources/Repository/LyricRepositoryImpl.swift
  Projects/Domains/LyricDomain/Sources/ResponseDTO/DecoratingBackgroundResponseDTO.swift
  Projects/Domains/LyricDomain/Sources/UseCase/FetchDecoratingBackgroundUseCaseImpl.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartViewController.swift
  Projects/Features/LyricHighlightingFeature/Project.swift
  Projects/Features/LyricHighlightingFeature/Sources/Components/LyricDecoratingComponent.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricDecoratingViewModel.swift
  Projects/Features/LyricHighlightingFeature/Sources/Views/LyricDecoratingCell.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#660 🔀 :: (#659) iOS 최소 지원 버전 상향
  Plugin/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/BaseReactorViewController.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/BaseStoryboardReactorViewController.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/BaseViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/MyInfoNavigationButton.swift
  Projects/Modules/Utility/Sources/Utils/Utils.swift
  Projects/UsertInterfaces/DesignSystem/Sources/VerticalAlignButton.swift
Labels: 🌏 Deploy, 2️⃣ Priority: Medium

#658 🔀 :: (#657) 최신음악: 업데이트 시간 제거
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#662 🔀 :: (#630) 가사 하이라이팅 UI 변경 대응
  Projects/App/Support/Info.plist
  Projects/Features/ArtistFeature/Project.swift
  Projects/Features/ArtistFeature/Sources/Components/ArtistComponent.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
  Projects/Features/BaseFeature/Sources/Protocols/RequestPermissionable.swift
  Projects/Features/LyricHighlightingFeature/Sources/Components/LyricDecoratingComponent.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController+Bind.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController+Bind.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricDecoratingViewModel.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
  Projects/Features/LyricHighlightingFeature/Sources/Views/LyricDecoratingCell.swift
  Projects/Features/LyricHighlightingFeature/Sources/Views/LyricHighlightingCell.swift
  Projects/UsertInterfaces/DesignSystem/Sources/VerticalAlignButton.swift
  graph.png
Labels: 1️⃣ Priority: High, ⚡️ Performance

#667 🔀 :: (666) 로그인이 안되던 문제 해결
  Projects/Domains/UserDomain/Sources/ResponseDTO/FetchUserResponseDTO.swift
  Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
Labels: 0️⃣ Priority: Critical

#675 🔀 :: (#567) 내 정보 화면 구현
  Projects/App/Sources/Application/AppComponent+Image.swift
  Projects/App/Sources/Application/AppComponent+MyInfo.swift
  Projects/App/Sources/Application/AppComponent+User.swift
  Projects/Domains/ImageDomain/Interface/DataSource/RemoteImageDataSource.swift
  Projects/Domains/ImageDomain/Interface/Entity/ProfileListEntity.swift
  Projects/Domains/ImageDomain/Interface/Repository/ImageRepository.swift
  Projects/Domains/ImageDomain/Interface/UseCase/FetchProfileListUseCase.swift
  Projects/Domains/ImageDomain/Sources/API/ImageAPI.swift
  Projects/Domains/ImageDomain/Sources/DataSource/RemoteImageDataSourceImpl.swift
  Projects/Domains/ImageDomain/Sources/Repository/ImageRepositoryImpl.swift
  Projects/Domains/ImageDomain/Sources/ResponseDTO/FetchProfileListResponseDTO.swift
  Projects/Domains/ImageDomain/Sources/UseCase/FetchProfileListUseCaseImpl.swift
  Projects/Domains/UserDomain/Interface/DataSource/RemoteUserDataSource.swift
  Projects/Domains/UserDomain/Interface/Repository/UserRepository.swift
  Projects/Domains/UserDomain/Interface/UseCase/FetchProfileListUseCase.swift
  Projects/Domains/UserDomain/Sources/API/UserAPI.swift
  Projects/Domains/UserDomain/Sources/DataSource/RemoteUserDataSourceImpl.swift
  Projects/Domains/UserDomain/Sources/Repository/UserRepositoryImpl.swift
  Projects/Domains/UserDomain/Sources/RequestDTO/EditFavoriteSongsOrderRequestDTO.swift
  Projects/Domains/UserDomain/Sources/RequestDTO/EditPlayListOrderRequestDTO.swift
  Projects/Domains/UserDomain/Sources/RequestDTO/SetProfileRequestDTO.swift
  Projects/Domains/UserDomain/Sources/RequestDTO/SetUserNameRequestDTO.swift
  Projects/Domains/UserDomain/Sources/UseCase/FetchProfileListUseCaseImpl.swift
  Projects/Features/BaseFeature/Sources/ViewModels/MultiPurposePopupViewModel.swift
  Projects/Features/MyInfoFeature/Project.swift
  Projects/Features/MyInfoFeature/Resources/ProfilePopUp.storyboard
  Projects/Features/MyInfoFeature/Sources/Components/MyInfoComponent.swift
  Projects/Features/MyInfoFeature/Sources/Components/ProfilePopComponent.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/ProfilePopup/ProfilePopViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/ProfilePopViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Views/MyInfoView.swift
  Projects/Features/MyInfoFeature/Sources/Views/ProfileCollectionViewCell.swift
  Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift
  Projects/Features/StorageFeature/Resources/Storage.storyboard
Labels: 1️⃣ Priority: High, ✨ Feature

#680 🔀 :: (#679) "UIApplication.shared.windows" 잔존 코드 제거
  Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
  Projects/Features/BaseFeature/Sources/Views/BottomSheet/BottomSheetCalculator.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SearchViewController.swift
  Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
  Projects/Modules/Utility/Sources/GoogleOAuth/GoogleLoginManager.swift
Labels: ⚡️ Simple, 2️⃣ Priority: Medium

#678 🔀 :: (#677) playlistDomain에 명시된 Usecase를 MyPlaylistVC에 미리 명시해둡니다.
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/Features/PlaylistFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/PlaylistFeature/Interface/MyPlaylistFactory.swift
  Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Tests/MyPlaylistDetailSpec.swift
  Projects/Features/StorageFeature/Resources/Storage.storyboard
  Projects/Features/StorageFeature/Sources/Components/PlaylistStorageComponent.swift
  Projects/Features/StorageFeature/Sources/Components/StorageComponent.swift
  Projects/Features/StorageFeature/Sources/Reactors/PlaylistStorageReactor.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/PlaylistStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#683 🔀 :: (#682) SignInFeature 리팩토링
  Projects/Features/BaseFeature/Resources/Base.storyboard
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/SignInFeature/Resources/SignIn.storyboard
  Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
  Projects/Modules/Utility/Sources/GoogleOAuth/GoogleLoginManager.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor

#686 🔀 :: (#624) 오픈소스 라이선스 정리
  Projects/Features/MyInfoFeature/Sources/ViewModels/OpenSourceLicenseViewModel.swift
Labels: 3️⃣ Priority: Low

#691 🔀 :: (#685) Multipurpose VC에서 Usecase를 제거합니다.
  Projects/App/Sources/Application/AppComponent+Base.swift
  Projects/Features/BaseFeature/Interface/MultipurposePopUp/MultiPurposePopupFactory.swift
  Projects/Features/BaseFeature/Sources/Components/ContainSongsComponent.swift
  Projects/Features/BaseFeature/Sources/Components/MultiPurposePopUpComponent.swift
  Projects/Features/BaseFeature/Sources/Components/MultiPurposePopupComponent.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
  Projects/Features/BaseFeature/Sources/ViewModels/MultiPurposePopupViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Components/MyInfoComponent.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/PlayListDetailComponent.swift
  Projects/Features/StorageFeature/Sources/Components/PlaylistStorageComponent.swift
  Projects/Features/StorageFeature/Sources/Components/StorageComponent.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/PlaylistStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
Labels: ⚡️ Simple, ⚡️ Performance, ♻️ Refactor

#695 🔀 :: (#694) ArtistFeature 애널리틱스 로그 심기
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/Features/ArtistFeature/Sources/Analytics/ArtistAnalyticsLog.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
  Projects/Features/ArtistFeature/Sources/Views/ArtistListCell.swift
  Projects/Features/ArtistFeature/Sources/Views/ArtistMusicCell.swift
  Projects/Features/ArtistFeature/Sources/Views/ArtistPlayButtonGroupView.swift
Labels: ✨ Feature, 2️⃣ Priority: Medium

#701 🔀 :: (#700) ArtistFeature 애널리틱스 로그 심기 (view_page 누락)
  Projects/Features/ArtistFeature/Sources/Analytics/ArtistAnalyticsLog.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#698 🔀 :: (#697) 가사 하이라이팅 > 흐르는 레이블 적용
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
Labels: ⚡️ Simple, ✨ Feature, 3️⃣ Priority: Low

#696 🔀 :: (#674) 공지사항 전부 읽었는지 판별 기능
  Projects/App/Sources/Application/AppComponent+Notice.swift
  Projects/Domains/NoticeDomain/Interface/DataSource/RemoteNoticeDataSource.swift
  Projects/Domains/NoticeDomain/Interface/Entity/FetchNoticeCategoriesEntity.swift
  Projects/Domains/NoticeDomain/Interface/Entity/FetchNoticeEntity.swift
  Projects/Domains/NoticeDomain/Interface/Entity/FetchNoticeIDListEntity.swift
  Projects/Domains/NoticeDomain/Interface/Enum/NoticeType.swift
  Projects/Domains/NoticeDomain/Interface/Repository/NoticeRepository.swift
  Projects/Domains/NoticeDomain/Interface/UseCase/FetchNoticeAllUseCase.swift
  Projects/Domains/NoticeDomain/Interface/UseCase/FetchNoticeCategoriesUseCase.swift
  Projects/Domains/NoticeDomain/Interface/UseCase/FetchNoticeIDListUseCase.swift
  Projects/Domains/NoticeDomain/Interface/UseCase/FetchNoticePopupUseCase.swift
  Projects/Domains/NoticeDomain/Interface/UseCase/FetchNoticeUseCase.swift
  Projects/Domains/NoticeDomain/Sources/API/NoticeAPI.swift
  Projects/Domains/NoticeDomain/Sources/DataSource/RemoteNoticeDataSourceImpl.swift
  Projects/Domains/NoticeDomain/Sources/Repository/NoticeRepositoryImpl.swift
  Projects/Domains/NoticeDomain/Sources/ResponseDTO/FetchNoticeCategoriesResponseDTO.swift
  Projects/Domains/NoticeDomain/Sources/ResponseDTO/FetchNoticeIDListDTO.swift
  Projects/Domains/NoticeDomain/Sources/ResponseDTO/FetchNoticeResponseDTO.swift
  Projects/Domains/NoticeDomain/Sources/UseCase/FetchNoticeAllUseCaseImpl.swift
  Projects/Domains/NoticeDomain/Sources/UseCase/FetchNoticeIDListUseCaseImpl.swift
  Projects/Domains/NoticeDomain/Sources/UseCase/FetchNoticePopupUseCaseImpl.swift
  Projects/Domains/NoticeDomain/Testing/FetchNoticeAllUseCaseStub.swift
  Projects/Domains/NoticeDomain/Testing/FetchNoticeUseCaseStub.swift
  Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/NoticePopupViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewModels/MainTabBarViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Components/MyInfoComponent.swift
  Projects/Features/MyInfoFeature/Sources/Components/NoticeComponent.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/NoticeDetailViewModel.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/NoticeViewModel.swift
  Projects/Features/MyInfoFeature/Testing/NoticeComponentStub.swift
  Projects/Modules/Utility/Sources/Manager/PreferenceManager.swift
Labels: ✨ Feature, 2️⃣ Priority: Medium, 🚀 API

#702 🔀 :: (#693) 에딧 시트 숨기기 기능
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/MyInfoView.swift
Labels: ✨ Feature, 3️⃣ Priority: Low

#705 🔀 :: (#699) connect usecase fruit draw 외 4
  Projects/App/Sources/Application/AppComponent+User.swift
  Projects/Domains/UserDomain/Interface/DataSource/RemoteUserDataSource.swift
  Projects/Domains/UserDomain/Interface/Entity/FruitDrawStatusEntity.swift
  Projects/Domains/UserDomain/Interface/Entity/FruitEntity.swift
  Projects/Domains/UserDomain/Interface/Repository/UserRepository.swift
  Projects/Domains/UserDomain/Interface/UseCase/DrawFruitUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/FetchFruitDrawStatusUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/FetchFruitListUseCase.swift
  Projects/Domains/UserDomain/Sources/API/UserAPI.swift
  Projects/Domains/UserDomain/Sources/DataSource/RemoteUserDataSourceImpl.swift
  Projects/Domains/UserDomain/Sources/Repository/UserRepositoryImpl.swift
  Projects/Domains/UserDomain/Sources/ResponseDTO/FruitDrawStatusResponseDTO.swift
  Projects/Domains/UserDomain/Sources/ResponseDTO/FruitListResponseDTO.swift
  Projects/Domains/UserDomain/Sources/UseCase/DrawFruitUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/FetchFruitDrawStatusUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/FetchFruitListUseCaseImpl.swift
  Projects/Features/FruitDrawFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/FruitDrawFeature/Interface/FruitDrawFactory.swift
  Projects/Features/FruitDrawFeature/Project.swift
  Projects/Features/FruitDrawFeature/Sources/Components/FruitDrawComponent.swift
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitDrawViewController.swift
  Projects/Features/FruitDrawFeature/Sources/ViewModels/FruitDrawViewModel.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/RootFeature/Project.swift
  Projects/Features/RootFeature/Sources/ViewControllers/IntroViewController.swift
  Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
Labels: 1️⃣ Priority: High, ✨ Feature, 🚀 API

#711 🔀 :: (#706) 열매함 화면 구현
  Projects/App/Sources/Application/AppComponent+Fruit.swift
  Projects/App/Sources/Application/AppComponent+MyInfo.swift
  Projects/Domains/UserDomain/Sources/ResponseDTO/FruitListResponseDTO.swift
  Projects/Features/FruitDrawFeature/Interface/FruitStorageFactory.swift
  Projects/Features/FruitDrawFeature/Sources/Components/FruitStorageComponent.swift
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitInfoPopupViewController.swift
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitStorageViewController.swift
  Projects/Features/FruitDrawFeature/Sources/ViewModels/FruitStorageViewModel.swift
  Projects/Features/FruitDrawFeature/Sources/Views/FruitListCell.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController+Bind.swift
  Projects/Features/LyricHighlightingFeature/Sources/Views/LyricDecoratingCell.swift
  Projects/Features/MyInfoFeature/Sources/Components/MyInfoComponent.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/MyInfoView.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/note_info_popup_bg.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/note_info_popup_bg.imageset/note_info_popup_bg@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/note_info_popup_bg.imageset/note_info_popup_bg@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/note_support.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/note_support.imageset/note_support@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/note_support.imageset/note_support@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note.imageset/Group 2607997@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note.imageset/Group 2607997@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_1st.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_1st.imageset/unidentified_note_1st@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_1st.imageset/unidentified_note_1st@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_2nd.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_2nd.imageset/unidentified_note_2nd@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_2nd.imageset/unidentified_note_2nd@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_3rd.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_3rd.imageset/unidentified_note_3rd@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_3rd.imageset/unidentified_note_3rd@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_4th.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_4th.imageset/unidentified_note_4th@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_4th.imageset/unidentified_note_4th@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_5th.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_5th.imageset/unidentified_note_5th@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_5th.imageset/unidentified_note_5th@3x.png
  Projects/UsertInterfaces/DesignSystem/Sources/WMNavigationBarView.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#707 🔀 :: (#681) 설정 화면을 추가 구현합니다.
  Projects/Domains/AuthDomain/Interface/DataSource/RemoteAuthDataSource.swift
  Projects/Domains/AuthDomain/Sources/API/AuthAPI.swift
  Projects/Domains/AuthDomain/Sources/DataSource/RemoteAuthDataSourceImpl.swift
  Projects/Domains/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domains/AuthDomain/Sources/UseCase/LogoutUseCaseImpl.swift
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/MyInfoFeature/Interface/Enum/SettingItemCategory.swift
  Projects/Features/MyInfoFeature/Interface/Enum/SettingItemType.swift
  Projects/Features/MyInfoFeature/Interface/Protocol/Factory.swift
  Projects/Features/MyInfoFeature/Sources/DataSource/SettingItemDataSource.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/SettingReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/ProfilePopViewModel.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/RequestViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Views/SettingItemButton.swift
  Projects/Features/MyInfoFeature/Sources/Views/SettingItemTableViewCell.swift
  Projects/Features/MyInfoFeature/Sources/Views/SettingView.swift
Labels: ✨ Feature, 2️⃣ Priority: Medium

#714 🔀 :: (#670) 프로필 이미지 불러오기 DTO 변경사항 반영
  Projects/Domains/ImageDomain/Interface/Entity/ProfileListEntity.swift
  Projects/Domains/ImageDomain/Sources/ResponseDTO/FetchProfileListResponseDTO.swift
  Projects/Features/MyInfoFeature/Resources/ProfilePopUp.storyboard
  Projects/Features/MyInfoFeature/Sources/ViewControllers/ProfilePopup/ProfilePopViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/ProfilePopViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Views/ProfileCollectionViewCell.swift
  Projects/Features/MyInfoFeature/Sources/Views/ProfileView.swift
  Projects/Modules/Utility/Sources/API/WMImageAPI.swift
Labels: 1️⃣ Priority: High, 🚀 API
