Repository wakmusic/wakmusic-iOS, pull requests merged in 2024-04, with the labels that each got.

#480 🔀 :: (#479) Unit Test 모듈에 Quick, Nimble 의존성 추가
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/BaseFeature/Project.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+Template.swift
  Tuist/ProjectDescriptionHelpers/Target/Target+MicroFeatures.swift
Labels: ⚙ Setting

#481 🔀 :: (#478) Reactor전용 BaseViewController 추가
  Projects/Features/BaseFeature/Sources/BaseReactorViewController.swift
  Projects/Features/BaseFeature/Sources/BaseStoryboardReactorViewController.swift
Labels: ✨ Feature

#485 🔀 :: (#477) 리프레시 토큰 대응
  Projects/Domains/BaseDomain/Sources/Jwt/JwtAuthorizable.swift
  Projects/Domains/BaseDomain/Sources/Jwt/JwtPlugin.swift
  Projects/Domains/BaseDomain/Sources/ResponseDTO/TokenDTO.swift
  Projects/Modules/KeychainModule/Sources/Keychain.swift
Labels: ♻️ Refactor

#486 🔀 :: (#477) Logout UseCase 추가
  Projects/App/Sources/Application/AppComponent+Auth.swift
  Projects/Domains/AuthDomain/Interface/DataSource/LocalAuthDataSource.swift
  Projects/Domains/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domains/AuthDomain/Interface/UseCase/LogoutUseCase.swift
  Projects/Domains/AuthDomain/Sources/DataSource/LocalAuthDataSourceImpl.swift
  Projects/Domains/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domains/AuthDomain/Sources/UseCase/LogoutUseCaseImpl.swift
Labels: ♻️ Refactor

#487 🔀 :: (#477) Feature 레이어의 로그아웃 로직 리팩토링
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/CommonFeature/Sources/Components/ContainSongsComponent.swift
  Projects/Features/CommonFeature/Sources/Components/MultiPurposePopComponent.swift
  Projects/Features/CommonFeature/Sources/Components/PlayListDetailComponent.swift
  Projects/Features/CommonFeature/Sources/Components/ProfilePopComponent.swift
  Projects/Features/CommonFeature/Sources/ViewControllers/ContainSongsViewController.swift
  Projects/Features/CommonFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
  Projects/Features/CommonFeature/Sources/ViewControllers/PlayListDetailViewController.swift
  Projects/Features/CommonFeature/Sources/ViewControllers/ProfilePopViewController.swift
  Projects/Features/CommonFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/CommonFeature/Sources/ViewModels/MultiPurposePopupViewModel.swift
  Projects/Features/CommonFeature/Sources/ViewModels/PlayListDetailViewModel.swift
  Projects/Features/CommonFeature/Sources/ViewModels/ProfilePopViewModel.swift
  Projects/Features/PlayerFeature/Sources/Components/PlayerComponent.swift
  Projects/Features/PlayerFeature/Sources/ViewControllers/PlayerViewController.swift
  Projects/Features/PlayerFeature/Sources/ViewModels/PlayerViewModel.swift
  Projects/Features/StorageFeature/Sources/Components/FavoriteComponent.swift
  Projects/Features/StorageFeature/Sources/Components/MyPlayListComponent.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/MyPlayListViewController.swift
  Projects/Features/StorageFeature/Sources/ViewModels/FavoriteViewModel.swift
  Projects/Features/StorageFeature/Sources/ViewModels/MyPlayListViewModel.swift
  Projects/Modules/Utility/Sources/Utils/Utils.swift
Labels: ♻️ Refactor

#488 🔀 :: (#477) Feature 레이어에서의 keychain 직접 사용 코드 리팩토링
  Projects/App/Sources/Application/AppComponent+Auth.swift
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Domains/AuthDomain/Interface/DataSource/LocalAuthDataSource.swift
  Projects/Domains/AuthDomain/Interface/Repository/AuthRepository.swift
  Projects/Domains/AuthDomain/Interface/UseCase/CheckIsExistAccessTokenUseCase.swift
  Projects/Domains/AuthDomain/Sources/DataSource/LocalAuthDataSourceImpl.swift
  Projects/Domains/AuthDomain/Sources/Repository/AuthRepositoryImpl.swift
  Projects/Domains/AuthDomain/Sources/UseCase/CheckIsExistAccessTokenUseCaseImpl.swift
  Projects/Features/RootFeature/Sources/Components/RootComponent.swift
  Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
  Projects/Features/StorageFeature/Sources/Components/AfterLoginComponent.swift
  Projects/Features/StorageFeature/Sources/Components/RequestComponent.swift
  Projects/Features/StorageFeature/Sources/ViewModels/AfterLoginStorageViewModel.swift
  Projects/Features/StorageFeature/Sources/ViewModels/RequestViewModel.swift
Labels: ♻️ Refactor

#497 🔀 :: (#496) Analytics를 위한 로깅 매니저 추가
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/Modules/LogManager/Project.swift
  Projects/Modules/LogManager/Sources/AnalyticsLogManager.swift
  Projects/Modules/LogManager/Sources/AnalyticsLogType.swift
  Projects/Modules/LogManager/Sources/CommonAnalyticsLog.swift
  Projects/Modules/Utility/Project.swift
Labels: 1️⃣ Priority: High, ⚙ Setting

#503 🔀 :: (#499) Inject 적용
  .package.resolved
  Plugin/ConfigurationPlugin/ProjectDescriptionHelpers/Configuration+Ext.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Features/BaseFeature/Project.swift
  Projects/Modules/Utility/Sources/Utils/Utils.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/Project/Project+Template.swift
  Tuist/ProjectDescriptionHelpers/Target/Target+MicroFeatures.swift
Labels: ⚙ Setting

#504 🔀 :: (#494) 아티스트 페이지 리팩토링
  Projects/App/Sources/Application/NeedleGenerated.swift
  Projects/Features/ArtistFeature/Sources/Reactors/ArtistReactor.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailHeaderViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
  Projects/Features/ArtistFeature/Tests/ArtistReactorTests.swift
Labels: 🐞 Bug, ♻️ Refactor
