Repository wakmusic/wakmusic-iOS, pull requests merged in 2024-07, with the labels that each got.

#717 🔀 :: (#716) 바텀시트 일원화
  Projects/Features/BaseFeature/Sources/Protocols/WMBottomSheetViewType.swift
  Projects/Features/BaseFeature/Sources/Views/WMBottomSheetView.swift
Labels: 1️⃣ Priority: High, ♻️ Refactor

#703 🔀 :: (#692) MyPlaylist에 필요한 의존성 주입을 마무리합니다.
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/Domains/PlaylistDomain/Sources/API/PlaylistAPI.swift
  Projects/Features/BaseFeature/Interface/Enum/PurposeType.swift
  Projects/Features/BaseFeature/Sources/Protocols/SongCartViewType.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/MultiPurposePopupViewController.swift
  Projects/Features/BaseFeature/Sources/Views/SongCartView.swift
  Projects/Features/PlaylistFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/PlaylistFeature/Project.swift
  Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Model/MyPlaylistHeaderModel.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/MyPlaylistHeaderView.swift
  Projects/Features/PlaylistFeature/Tests/MyPlaylistDetailSpec.swift
  Projects/Features/SearchFeature/Sources/Components/BeforeSearchComponent.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/PlaylistStorageViewController.swift
  graph.png
Labels: 1️⃣ Priority: High, ⚡️ Simple, ⚡️ Performance

#719 🔀 :: (#704) 커스텀 플레이 리스트를 갤러리에서 가져와 적용합니다 (Pending)
  Projects/Features/BaseFeature/Sources/Protocols/PlaylistImageEditSheetViewType.swift
  Projects/Features/BaseFeature/Sources/Protocols/RequestPermissionable.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/MyPlaylistHeaderView.swift
Labels: ⚡️ Performance, ✨ Feature, 2️⃣ Priority: Medium

#720 🔀 :: (#710) containsSong 변경사항 반영
  Projects/Domains/UserDomain/Interface/DataSource/RemoteUserDataSource.swift
  Projects/Domains/UserDomain/Interface/Entity/PlaylistEntity.swift
  Projects/Domains/UserDomain/Interface/Repository/UserRepository.swift
  Projects/Domains/UserDomain/Interface/UseCase/FetchPlayListUseCase.swift
  Projects/Domains/UserDomain/Sources/DataSource/RemoteUserDataSourceImpl.swift
  Projects/Domains/UserDomain/Sources/Repository/UserRepositoryImpl.swift
  Projects/Domains/UserDomain/Sources/ResponseDTO/PlayListResponseDTO.swift
  Projects/Domains/UserDomain/Sources/ResponseDTO/PlaylistResponseDTO.swift
  Projects/Domains/UserDomain/Sources/UseCase/FetchPlayListUseCaseImpl.swift
  Projects/Features/BaseFeature/Sources/Components/ContainSongsComponent.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/BaseFeature/Sources/Views/CurrentPlayListTableViewCell.swift
  Projects/Features/PlaylistFeature/Tests/MyPlaylistDetailSpec.swift
  Projects/Features/StorageFeature/Sources/Reactors/PlaylistStorageReactor.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/PlaylistStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewModels/MyPlayListViewModel.swift
  Projects/Features/StorageFeature/Sources/Views/MyPlayListTableViewCell.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#718 🔀 :: (#715) 공지사항 리스트에 읽었는지 여부 인디케이터 추가
  Projects/Domains/NoticeDomain/Interface/Entity/FetchNoticeEntity.swift
  Projects/Domains/NoticeDomain/Testing/FetchNoticeAllUseCaseStub.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Notice/NoticeViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/NoticeViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Views/NoticeListCell.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MyInfo.xcassets/red_dot.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MyInfo.xcassets/red_dot.imageset/dot.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MyInfo.xcassets/red_dot.imageset/dot@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MyInfo.xcassets/red_dot.imageset/dot@3x.png
Labels: ✨ Feature, 2️⃣ Priority: Medium

#726 🔀 :: (#721) 익명 플레이리스트를 구현합니다.
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/Domains/PlaylistDomain/Interface/DataSource/RemotePlaylistDataSource.swift
  Projects/Domains/PlaylistDomain/Interface/Enum/PlaylistType.swift
  Projects/Domains/PlaylistDomain/Interface/Repository/PlaylistRepository.swift
  Projects/Domains/PlaylistDomain/Interface/UseCase/SubscribePlaylistUseCase.swift
  Projects/Domains/PlaylistDomain/Interface/UseCase/UnSubscribePlaylistUseCase.swift
  Projects/Domains/PlaylistDomain/Sources/API/PlaylistAPI.swift
  Projects/Domains/PlaylistDomain/Sources/DataSource/RemotePlaylistDataSourceImpl.swift
  Projects/Domains/PlaylistDomain/Sources/Repository/PlaylistRepositoryImpl.swift
  Projects/Domains/PlaylistDomain/Sources/UseCase/SubscribePlaylistUseCaseImpl.swift
  Projects/Domains/PlaylistDomain/Sources/UseCase/UnSubscribePlaylistUseCaseImpl.swift
  Projects/Domains/SongsDomain/Sources/ResponseDTO/SingleSongResponseDTO.swift
  Projects/Features/PlaylistFeature/Interface/MyPlaylistDetailFactory.swift
  Projects/Features/PlaylistFeature/Interface/UnknownPlaylistDetailFactory.swift
  Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/UnkwonPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/DataSource/MyPlaylistDetailDataSource.swift
  Projects/Features/PlaylistFeature/Sources/DataSource/UnkwonPlaylistDetailDataSource.swift
  Projects/Features/PlaylistFeature/Sources/Model/PlaylistDetailHeaderModel.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/MyPlaylistHeaderView.swift
  Projects/Features/PlaylistFeature/Sources/Views/PlaylistDateTableViewCell.swift
  Projects/Features/PlaylistFeature/Sources/Views/UnknownPlaylistHeaderView.swift
  Projects/Features/PlaylistFeature/Tests/MyPlaylistDetailSpec.swift
  Projects/Features/SearchFeature/Sources/Components/BeforeSearchComponent.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Playlist.xcassets/grayDot.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Playlist.xcassets/grayDot.imageset/grayDot@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Playlist.xcassets/grayDot.imageset/grayDot@3x.png
Labels: 1️⃣ Priority: High, ✨ Feature

#731 🔀 :: (#730) 로그인 화면:: 메인스레드 익셉션 오류 해결
  Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#732 🔀 :: (#712) 열매 뽑기:: 로티 연결
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitDrawViewController.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Lottie/Fruit_Draw.json
Labels: 1️⃣ Priority: High, ⚡️ Simple, ✨ Feature

#733 🔀 :: (#654) PlayState 데이터 캡슐화 및 외부 의존성 제거
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Songs.swift
  Projects/Domains/SongsDomain/Interface/Entity/SongEntity.swift
  Projects/Domains/SongsDomain/Sources/ResponseDTO/SingleSongResponseDTO.swift
  Projects/Domains/UserDomain/Sources/ResponseDTO/FavoriteSongsResponseDTO.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/Entity/PlaylistLocalEntity.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Public.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
  Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MusicDetailFeature/Interface/Interface.swift
  Projects/Features/MusicDetailFeature/Interface/MusicDetailFactory.swift
  Projects/Features/MusicDetailFeature/Sources/Component/MusicDetailComponent.swift
  Projects/Features/MusicDetailFeature/Sources/Model/PlaylistModel.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/DataSource/MyPlaylistDetailDataSource.swift
  Projects/Features/PlaylistFeature/Sources/Model/PlaylistItemModel.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewModels/PlayListViewModel.swift
  Projects/Features/PlaylistFeature/Sources/Views/PlaylistTableViewCell.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+String.swift
  Projects/Modules/Utility/Sources/Realm/RealmManager.swift
  Projects/Modules/Utility/Sources/Realm/RealmModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#737 🔀 :: (#736) 열매 뽑기:: 추가 수정사항 반영
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitDrawViewController.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#740 🔀 :: (#663) 유저 프로필 DTO 변경에 따른 대응
  Projects/Domains/UserDomain/Interface/Entity/UserInfoEntity.swift
  Projects/Domains/UserDomain/Sources/ResponseDTO/FetchUserResponseDTO.swift
  Projects/Domains/UserDomain/Testing/FetchUserInfoUserCaseSpy.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
  Projects/Features/StorageFeature/Sources/ViewModels/AfterLoginStorageViewModel.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+PreferenceManager.swift
  Projects/Modules/Utility/Sources/Manager/PreferenceManager.swift
  Projects/Modules/Utility/Sources/Manager/UserInfoManager.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple, 🚀 API

#747 🔀 :: (#744) 열매뽑기:: 로그심기
  Projects/Features/FruitDrawFeature/Sources/Analytics/FruitDrawAnalyticsLog.swift
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitDrawViewController.swift
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitStorageViewController.swift
  Projects/Modules/LogManager/Sources/AnalyticsLogType.swift
Labels: 1️⃣ Priority: High

#746 🔀 :: (#743) 가사 하이라이팅:: 로그 심기
  Projects/Features/LyricHighlightingFeature/Sources/Analytics/LyricHighlightingAnalyticsLog.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController+Bind.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricDecoratingViewController.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController+Bind.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricDecoratingViewModel.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewModels/LyricHighlightingViewModel.swift
Labels: 1️⃣ Priority: High

#752 🔀 :: (#751) 프리퍼런스 접근 개선
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/QuestionViewModel.swift
  Projects/Features/SignInFeature/Sources/ViewModels/LoginViewModel.swift
  Projects/Features/StorageFeature/Sources/ViewModels/AfterLoginStorageViewModel.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+PreferenceManager.swift
  Projects/Modules/Utility/Sources/Manager/UserInfoManager.swift
  Projects/Modules/Utility/Sources/Utils/AES256.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Performance

#741 🔀 :: (#735) 기본 플레이리스트 이미지 팝업을 만들고 연결합니다.
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/Features/PlaylistFeature/Interface/DefaultPlaylistImageFactory.swift
  Projects/Features/PlaylistFeature/Sources/Components/DefaultPlaylistImageComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/DefaultPlaylistImageReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/DefaultPlaylistImageViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/DefaultThumbnailCell.swift
  Projects/Features/PlaylistFeature/Sources/Views/MyPlaylistHeaderView.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#745 🔀 :: (#742) 플레이리스트 기본 이미지를 불러오는 UseCase를 연결합니다.
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/Domains/ImageDomain/Interface/DataSource/RemoteImageDataSource.swift
  Projects/Domains/ImageDomain/Interface/Entity/DefaultImageEntity.swift
  Projects/Domains/ImageDomain/Interface/Repository/ImageRepository.swift
  Projects/Domains/ImageDomain/Interface/UseCase/FetchDefaultPlaylistImageUseCase.swift
  Projects/Domains/ImageDomain/Sources/API/ImageAPI.swift
  Projects/Domains/ImageDomain/Sources/DataSource/RemoteImageDataSourceImpl.swift
  Projects/Domains/ImageDomain/Sources/Repository/ImageRepositoryImpl.swift
  Projects/Domains/ImageDomain/Sources/ResponseDTO/FetchDefaultImageResponseDTO.swift
  Projects/Domains/ImageDomain/Sources/UseCase/FetchDefaultPlaylistImageUseCaseImpl.swift
  Projects/Features/PlaylistFeature/Project.swift
  Projects/Features/PlaylistFeature/Sources/Components/DefaultPlaylistImageComponent.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/DefaultPlaylistImageReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/DefaultPlaylistImageViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/DefaultThumbnailCell.swift
Labels: 0️⃣ Priority: Critical, 🚀 API

#750 🔀 :: (#749) 플리 상세 이동 통합 프로토콜 구현
  Projects/Domains/SearchDomain/Interface/Entity/SearchPlaylistEntity.swift
  Projects/Domains/SearchDomain/Sources/DTO/SearchPlaylistDTO.swift
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/PlaylistFeature/Interface/PlaylistDetailFactory.swift
  Projects/Features/PlaylistFeature/Interface/PlaylistDetailNavigator.swift
  Projects/Features/PlaylistFeature/Sources/Components/PlayListDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/PlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Testing/PlaylistDetailFactoryStub.swift
  Projects/Features/SearchFeature/Sources/Components/BeforeSearchComponent.swift
  Projects/Features/SearchFeature/Sources/Components/ListSearchResultComponent.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/PlaylistStorageViewController.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Performance

#759 🔀 :: (#758) 비로그인 상태로 열매 뽑기 화면 진입 시 크래쉬
  Projects/Features/MyInfoFeature/Sources/Reactors/MyInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#753 🔀 :: (#739) Notification Domain
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Notification.swift
  Projects/App/Support/Info.plist
  Projects/Domains/BaseDomain/Sources/WMAPI/SecretURL.swift
  Projects/Domains/BaseDomain/Sources/WMAPI/WMAPI.swift
  Projects/Domains/NotificationDomain/Interface/DataSource/RemoteNotificationDataSource.swift
  Projects/Domains/NotificationDomain/Interface/Enum/NotificationUpdateType.swift
  Projects/Domains/NotificationDomain/Interface/Repository/NotificationRepository.swift
  Projects/Domains/NotificationDomain/Interface/UseCase/UpdateNotificationTokenUseCase.swift
  Projects/Domains/NotificationDomain/Project.swift
  Projects/Domains/NotificationDomain/Sources/API/NotificationAPI.swift
  Projects/Domains/NotificationDomain/Sources/DataSource/RemoteNotificationDataSourceImpl.swift
  Projects/Domains/NotificationDomain/Sources/Repository/NotificationRepositoryImpl.swift
  Projects/Domains/NotificationDomain/Sources/UseCase/UpdateNotificationTokenUseCaseImpl.swift
  Projects/Features/MainTabFeature/Project.swift
Labels: 1️⃣ Priority: High, 🚀 API

#754 🔀 :: (#661) 검색 전 화면 로딩 중에 써치바 포커싱 시 앱 종료 버그를 해결합니다.
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Enum/DataSource/BeforeVcDataSoruce.swift
  Projects/Features/SearchFeature/Sources/Reactors/BeforeSearchReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/ListSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/WakmusicRecommendReactor.swift
  Projects/Features/SearchFeature/Sources/View/PopularPlayListCell.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/WakmusicRecommendViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#763 🔀 :: (#762) 검색 탭 디자인 검수 완료
  Projects/Domains/SearchDomain/Interface/Enum/Option.swift
  Projects/Features/SearchFeature/Resources/Search.storyboard
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/BeforeSearchCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/RecommendCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/View/ListResultCell.swift
  Projects/Features/SearchFeature/Sources/View/SearchFilterCell.swift
  Projects/Features/SearchFeature/Sources/View/SearchSortOptionCell.swift
  Projects/Features/SearchFeature/Sources/View/SongResultCell.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SearchSortOptionViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/WakmusicRecommendViewController.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#764 🔀 :: (#632) 검색 탭 에러 처리 및 로그 주입하기
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/SearchFeature/Sources/Analytics/SearchAnalyticsLog.swift
  Projects/Features/SearchFeature/Sources/Reactors/ListSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/WakmusicRecommendViewController.swift
Labels: 1️⃣ Priority: High, ⚡️ Performance

#768 🔀 :: (#722) 보관함 탭을 구현합니다.
  Projects/App/Sources/Application/AppComponent+Auth.swift
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/App/Sources/Application/AppComponent+Storage.swift
  Projects/App/Sources/Application/AppComponent+User.swift
  Projects/Domains/UserDomain/Interface/DataSource/RemoteUserDataSource.swift
  Projects/Domains/UserDomain/Interface/Entity/PlaylistEntity.swift
  Projects/Domains/UserDomain/Interface/Repository/UserRepository.swift
  Projects/Domains/UserDomain/Interface/UseCase/DeletePlaylistUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/EditPlayListOrderUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/EditPlaylistOrderUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/FetchPlayListUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/FetchPlaylistUseCase.swift
  Projects/Domains/UserDomain/Sources/API/UserAPI.swift
  Projects/Domains/UserDomain/Sources/DataSource/RemoteUserDataSourceImpl.swift
  Projects/Domains/UserDomain/Sources/Repository/UserRepositoryImpl.swift
  Projects/Domains/UserDomain/Sources/RequestDTO/EditPlaylistOrderRequestDTO.swift
  Projects/Domains/UserDomain/Sources/UseCase/DeletePlaylistUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/EditFavoriteSongsOrderUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/EditPlaylistOrderUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/FetchPlaylistUseCaseImpl.swift
  Projects/Domains/UserDomain/Testing/FetchPlaylistUseCaseStub.swift
  Projects/Features/BaseFeature/Sources/Components/ContainSongsComponent.swift
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Views/SettingView.swift
  Projects/Features/StorageFeature/Resources/Storage.storyboard
  Projects/Features/StorageFeature/Sources/Components/LikeStorageComponent.swift
  Projects/Features/StorageFeature/Sources/Components/ListStorageComponent.swift
  Projects/Features/StorageFeature/Sources/Components/PlaylistStorageComponent.swift
  Projects/Features/StorageFeature/Sources/Components/StorageComponent.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/PlaylistStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/StorageReactor.swift
  Projects/Features/StorageFeature/Sources/Service/StorageCommonService.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/PlaylistStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewModels/MyPlayListViewModel.swift
  Projects/Features/StorageFeature/Sources/Views/CreateListButton.swift
  Projects/Features/StorageFeature/Sources/Views/LikeStorageView.swift
  Projects/Features/StorageFeature/Sources/Views/ListStorageTableViewCell.swift
  Projects/Features/StorageFeature/Sources/Views/ListStorageView.swift
  Projects/Features/StorageFeature/Sources/Views/MyPlayListTableViewCell.swift
  Projects/Features/StorageFeature/Sources/Views/StorageView.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+CALayer.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIColor.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Views/LoginWarningView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#767 🔀 :: (#765) 플레이리스트 디테일 디자인 검수
  Projects/Features/PlaylistFeature/Sources/Analytics/PlaylistAnalyticsLog.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/MyPlaylistHeaderView.swift
  Projects/Features/PlaylistFeature/Sources/Views/PlaylistDateTableViewCell.swift
  Projects/Features/PlaylistFeature/Sources/Views/UnknownPlaylistHeaderView.swift
  Projects/Features/PlaylistFeature/Sources/Views/WakmusicPlaylistHeaderView.swift
  Projects/Features/SearchFeature/Sources/Analytics/SearchAnalyticsLog.swift
  Projects/Features/SearchFeature/Sources/View/ListResultCell.swift
  Projects/Features/SearchFeature/Sources/View/SongResultCell.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/ViewControllers/WakmusicRecommendViewController.swift
  Projects/Modules/LogManager/Sources/CommonAnalyticsLog.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Extension+UILabel.swift
  Projects/UsertInterfaces/DesignSystem/Sources/WMLabel.swift
Labels: 0️⃣ Priority: Critical

#772 🔀 :: (#748) 접근 권한 안내 팝업 변경
  Projects/Features/RootFeature/Resources/Intro.storyboard
  Projects/Features/RootFeature/Sources/ViewControllers/PermissionViewController.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Permission.xcassets/permission_device.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Permission.xcassets/permission_device.imageset/permission_device@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Permission.xcassets/permission_device.imageset/permission_device@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Permission.xcassets/permission_notification.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Permission.xcassets/permission_notification.imageset/permission_notification@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Permission.xcassets/permission_notification.imageset/permission_notification@3x.png
Labels: 1️⃣ Priority: High

#774 🔀 :: (#769) 좋아요 탭을 구현합니다.
  Projects/Domains/UserDomain/Testing/FetchFavoriteSongsUseCaseStub.swift
  Projects/Domains/UserDomain/Testing/FetchPlaylistUseCaseStub.swift
  Projects/Features/StorageFeature/Resources/Storage.storyboard
  Projects/Features/StorageFeature/Sources/Components/LikeStorageComponent.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/FavoriteViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/LikeStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/StorageViewController.swift
  Projects/Features/StorageFeature/Sources/ViewModels/FavoriteViewModel.swift
  Projects/Features/StorageFeature/Sources/Views/EmptyWarningView.swift
  Projects/Features/StorageFeature/Sources/Views/FavoriteTableViewCell.swift
  Projects/Features/StorageFeature/Sources/Views/LikeStorageTableViewCell.swift
  Projects/Features/StorageFeature/Sources/Views/LikeStorageView.swift
  Projects/Features/StorageFeature/Sources/Views/ListStorageView.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#778 🔀 :: (#776) 검색 전 화면 왁뮤 추천플리 레이아웃 조절
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/BeforeSearchCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/CompositionalLayout/Layout/RecommendCollectionViewLayout.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#770 ♻️ :: (#654) PlayState API 노출 및 playlist 캡슐화
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Playlist.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState+Public.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlayState.swift
  Projects/Features/BaseFeature/Sources/Etc/PlayState/PlaylistItem.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewModels/PlayListViewModel.swift
  Projects/Features/PlaylistFeature/Sources/Views/PlaylistTableViewCell.swift
  Projects/Modules/Utility/Sources/Realm/RealmManager.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#784 🔀 :: (#431) 토큰 자동 리프레시 validation 로직 정상화
  Projects/Domains/BaseDomain/Sources/DataSource/BaseRemoteDataSource.swift
Labels: ⚡️ Performance, 2️⃣ Priority: Medium

#787 🔀 :: (#777) 비로그인 상태로 열매 뽑기 버튼을 누르면 앱이 터지는 문제를 수정합니다.
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/ViewControllers/ListStorageViewController.swift
  Projects/Features/StorageFeature/Sources/Views/CreateListButton.swift
  Projects/Features/StorageFeature/Sources/Views/EmptyWarningView.swift
  Projects/Features/StorageFeature/Sources/Views/LikeStorageView.swift
  Projects/Features/StorageFeature/Sources/Views/ListStorageView.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#783 🔀 :: (#782) Analytics 기본 파라미터 제거
  Projects/App/Sources/Application/AppDelegate.swift
  Projects/Modules/LogManager/Sources/AnalyticsLogManager.swift
  Projects/Modules/LogManager/Sources/AnalyticsLogType.swift
  Projects/Modules/LogManager/Sources/LogHistory/LogHistoryCell.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#786 🔀 :: (#780) 노래방 바텀 시트
  Projects/App/Sources/Application/AppComponent+Songs.swift
  Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MusicDetailFeature/Interface/KaraokeFactory.swift
  Projects/Features/MusicDetailFeature/Sources/Component/KaraokeComponent.swift
  Projects/Features/MusicDetailFeature/Sources/Model/KaraokeKind.swift
  Projects/Features/MusicDetailFeature/Sources/ViewControllers/KaraokeViewController.swift
  Projects/Features/MusicDetailFeature/Sources/Views/KaraokeContentView.swift
  Projects/Features/MusicDetailFeature/Sources/Views/KaraokeInfoView.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/ky.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/ky.imageset/ic_32_ky@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/ky.imageset/ic_32_ky@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/tj.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/tj.imageset/ic_32_tj@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/MusicDetail.xcassets/tj.imageset/ic_32_tj@3x.png
Labels: 1️⃣ Priority: High, ✨ Feature

#790 🔀 :: (#789) 열매함 디자인 수정사항 반영
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitInfoPopupViewController.swift
  Projects/Features/FruitDrawFeature/Sources/ViewControllers/FruitStorageViewController.swift
  Projects/Features/FruitDrawFeature/Sources/Views/FruitListCell.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Notice/NoticeViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Request/RequestViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/ServiceInfo/ServiceInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
  Projects/Features/SignInFeature/Sources/ViewControllers/LoginViewController.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_big.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_big.imageset/unidentified_note_big@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/FruitDraw.xcassets/unidentified_note_big.imageset/unidentified_note_big@3x.png
  Projects/UsertInterfaces/DesignSystem/Sources/Extension+UILabel.swift
  Projects/UsertInterfaces/DesignSystem/Sources/WMLabel.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#795 🔀 :: (#794) BasePlugin 추가
  Projects/Domains/AppDomain/Sources/API/AppAPI.swift
  Projects/Domains/BaseDomain/Sources/BasePlugin/BaseInfoSendable.swift
  Projects/Domains/BaseDomain/Sources/BasePlugin/BasePlugin.swift
  Projects/Domains/BaseDomain/Sources/DataSource/BaseRemoteDataSource.swift
  Projects/Domains/BaseDomain/Sources/WMAPI/WMAPI.swift
  Projects/Domains/NotificationDomain/Sources/API/NotificationAPI.swift
  Projects/Features/ArtistFeature/Project.swift
  Projects/Features/ArtistFeature/Sources/Components/ArtistComponent.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
  Projects/Modules/KeychainModule/Sources/Keychain.swift
Labels: 1️⃣ Priority: High, ⚡️ Performance

#806 🔀 :: (#805) SongEntity:: 미사용 프로퍼티 제거
  Projects/Domains/SongsDomain/Interface/Entity/SongEntity.swift
  Projects/Domains/SongsDomain/Sources/ResponseDTO/SingleSongResponseDTO.swift
  Projects/Domains/UserDomain/Sources/ResponseDTO/FavoriteSongsResponseDTO.swift
  Projects/Domains/UserDomain/Testing/FetchFavoriteSongsUseCaseStub.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
  Projects/Features/ArtistFeature/Sources/Views/ArtistMusicCell.swift
  Projects/Features/ChartFeature/Sources/ViewModels/ChartContentViewModel.swift
  Projects/Features/ChartFeature/Sources/Views/ChartContentTableViewCell.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
  Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
  Projects/Features/HomeFeature/Sources/Views/NewSongsCell.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Performance

#796 🔀 :: (#793) WakmusicPlayer 추가
  Projects/Modules/Utility/Sources/Player/WakmusicPlayer.swift
  Projects/Modules/Utility/Sources/Player/WakmusicYoutubePlayer.swift
  Projects/Modules/Utility/Sources/Youtube/YoutubeURLGenerator.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#797 🔀 :: (#771) 음악 상세 화면 로직 구현
  Package.resolved
  Package.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/Domains/SongsDomain/Project.swift
  Projects/Domains/SongsDomain/Testing/UseCase/FetchSongUseCaseSpy.swift
  Projects/Features/BaseFeature/Project.swift
  Projects/Features/HomeFeature/Sources/Components/HomeComponent.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/HomeFeature/Sources/Views/HomeChartCell.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController+Bind.swift
  Projects/Features/MainTabFeature/Sources/Components/MainContainerComponent.swift
  Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MusicDetailFeature/Interface/MusicDetailFactory.swift
  Projects/Features/MusicDetailFeature/Project.swift
  Projects/Features/MusicDetailFeature/Sources/Analytics/MusicDetailAnalyticsLog.swift
  Projects/Features/MusicDetailFeature/Sources/Component/MusicDetailComponent.swift
  Projects/Features/MusicDetailFeature/Sources/Model/PlaylistModel.swift
  Projects/Features/MusicDetailFeature/Sources/Model/SongModel.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetailReactor.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetailView.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetailViewController.swift
  Projects/Features/MusicDetailFeature/Sources/Views/ThumbnailCollectionView/ThumbnailCell.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#808 🔀 :: (#807) 홈화면 음악 상세 연결
  Projects/Features/HomeFeature/Resources/Home.storyboard
  Projects/Features/HomeFeature/Sources/Analytics/HomeAnalyticsLog.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
  Projects/Features/HomeFeature/Sources/Views/HomeNewSongCell.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#816 🔀 :: (#779) 팀 소개 화면 구현
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Sources/Application/AppComponent+MyInfo.swift
  Projects/App/Sources/Application/AppComponent+Team.swift
  Projects/Features/MainTabFeature/Project.swift
  Projects/Features/MyInfoFeature/Interface/Protocol/Factory.swift
  Projects/Features/MyInfoFeature/Project.swift
  Projects/Features/MyInfoFeature/Sources/Components/MyInfoComponent.swift
  Projects/Features/MyInfoFeature/Sources/Components/TeamInfoComponent.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/TeamInfoReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/MyInfo/MyInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/TeamInfo/TeamInfoViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/AppPushSettingView.swift
  Projects/Features/MyInfoFeature/Sources/Views/TeamInfoView.swift
  Projects/Features/MyInfoFeature/Testing/TeamInfoComponentStub.swift
  Projects/Features/TeamFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Features/TeamFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/TeamFeature/Interface/TeamInfoFactory.swift
  Projects/Features/TeamFeature/Interface/TeamInfoModel.swift
  Projects/Features/TeamFeature/Interface/TeamInfoType.swift
  Projects/Features/TeamFeature/Project.swift
  Projects/Features/TeamFeature/Sources/Components/TeamInfoComponent.swift
  Projects/Features/TeamFeature/Sources/ViewControllers/TeamInfoContentViewController.swift
  Projects/Features/TeamFeature/Sources/ViewControllers/TeamInfoViewController.swift
  Projects/Features/TeamFeature/Sources/ViewModels/TeamInfoContentViewModel.swift
  Projects/Features/TeamFeature/Sources/ViewModels/TeamInfoViewModel.swift
  Projects/Features/TeamFeature/Sources/Views/TeamInfoFooterView.swift
  Projects/Features/TeamFeature/Sources/Views/TeamInfoHeaderView.swift
  Projects/Features/TeamFeature/Sources/Views/TeamInfoListCell.swift
  Projects/Features/TeamFeature/Sources/Views/TeamInfoSectionView.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIView.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/arrow_bottom.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/arrow_bottom.imageset/arrow_bottom@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/arrow_bottom.imageset/arrow_bottom@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/arrow_top.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/arrow_top.imageset/arrow_top@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/arrow_top.imageset/arrow_top@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/crown.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/crown.imageset/crown@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/crown.imageset/crown@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/folder_off.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/folder_off.imageset/folder_off@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/folder_off.imageset/folder_off@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/folder_on.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/folder_on.imageset/folder_on@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Team.xcassets/folder_on.imageset/folder_on@3x.png
Labels: 1️⃣ Priority: High, ✨ Feature

#822 🔀 :: (#820) 차트:: 50곡 초과 선택 토스트 안내
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
Labels: 0️⃣ Priority: Critical

#821 🔀 :: (#819) 아티스트:: 50곡 초과 선택 토스트 안내
  Projects/Features/ArtistFeature/Resources/ArtistPlayButtonGroupView.xib
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
  Projects/Features/ArtistFeature/Sources/Views/ArtistPlayButtonGroupView.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
Labels: 0️⃣ Priority: Critical

#818 🔀 :: (#817) 최신음악:: 50곡 초과 선택 토스트 안내
  Projects/Features/ArtistFeature/Resources/ArtistPlayButtonGroupView.xib
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistMusicContentViewModel.swift
  Projects/Features/ArtistFeature/Sources/Views/ArtistPlayButtonGroupView.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewModels/NewSongsContentViewModel.swift
  Projects/UsertInterfaces/DesignSystem/Sources/SingleActionButtonView.swift
  graph.png
Labels: 0️⃣ Priority: Critical

#824 🔀 :: (#823) Testable import 제거
  Projects/Features/MusicDetailFeature/Project.swift
  Projects/Features/MusicDetailFeature/Sources/Component/MusicDetailComponent.swift
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#827 🔀 :: (#825) 공통으로 사용할 문자열을 strings에 정리해요.
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Features/BaseFeature/Project.swift
  Projects/Modules/Localization/Project.swift
  Projects/Modules/Localization/Resources/en.lproj/Localizable.strings
  Projects/Modules/Localization/Resources/ko.lproj/Localizable.strings
  Projects/Modules/Localization/Sources/Sources.swift
  Projects/UsertInterfaces/DesignSystem/Project.swift
Labels: 1️⃣ Priority: High, ⚡️ Performance

#832 🔀 :: (#831) LocalizationStrings 적용
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
Labels: ⚡️ Simple, 3️⃣ Priority: Low

#833 🔀 :: (#709) 앱 알림 받기 화면 구현
  Projects/App/Sources/Application/AppComponent+MyInfo.swift
  Projects/Features/MyInfoFeature/Interface/Enum/SettingItemCategory.swift
  Projects/Features/MyInfoFeature/Interface/Protocol/Factory.swift
  Projects/Features/MyInfoFeature/Sources/Components/AppPushSettingComponent.swift
  Projects/Features/MyInfoFeature/Sources/Components/SettingComponent.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/AppPushSettingReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/AppPushSetting/AppPushSettingViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
  Projects/Features/MyInfoFeature/Sources/Views/SettingItemTableViewCell.swift
  Projects/Features/MyInfoFeature/Testing/AppPushSettingComponentStub.swift
  Projects/Features/MyInfoFeature/Testing/SettingComponentStub.swift
Labels: ✨ Feature, 3️⃣ Priority: Low

#835 🔀 :: (#828) 플레이리스트 상세 플레이어 연결
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
  Projects/Modules/Localization/Resources/en.lproj/Localizable.strings
  Projects/Modules/Localization/Resources/ko.lproj/Localizable.strings
Labels: 1️⃣ Priority: High, ✨ Feature

#834 🔀 :: (#810) 크레딧 화면 UI 추가
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/Domains/SongsDomain/Testing/UseCase/FetchSongCreditsUseCaseSpy.swift
  Projects/Features/MusicDetailFeature/Project.swift
  Projects/Features/SongCreditFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Features/SongCreditFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/SongCreditFeature/Interface/Interface.swift
  Projects/Features/SongCreditFeature/Project.swift
  Projects/Features/SongCreditFeature/Sources/Model/CreditModel.swift
  Projects/Features/SongCreditFeature/Sources/SongCreditReactor.swift
  Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
  Projects/Features/SongCreditFeature/Sources/View/CreditCollectionView/CreditCollectionViewCell.swift
  Projects/Features/SongCreditFeature/Sources/View/CreditCollectionView/CreditCollectionViewLayout.swift
  Projects/Features/SongCreditFeature/Sources/View/CreditCollectionView/CreditCollectionViewPositionHeaderView.swift
  Projects/Features/SongCreditFeature/Testing/Testing.swift
  Projects/Features/SongCreditFeature/Tests/SongCreditFeatureTest.swift
  Projects/Modules/Localization/Resources/en.lproj/Localizable.strings
  Projects/Modules/Localization/Resources/ko.lproj/Localizable.strings
Labels: 0️⃣ Priority: Critical, ✨ Feature

#843 🔀 :: (#836) ContainSong에 제약 조건 및 에러 토스트 메시지 구현
  Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController+Delegate.swift
Labels: 1️⃣ Priority: High, ⚡️ Simple

#845 🔀 :: (#830) 검색화면에 50곡 제한 관련 메시지를 작성합니다.
  Projects/Features/SearchFeature/Sources/ViewControllers/SongSearchResultViewController.swift
Labels: 1️⃣ Priority: High, ⚡️ Performance

#847 🔀 :: (#844) 무한 스크롤 시 검색 패치를 여러번 하는 버그를 해결합니다.
  Projects/Features/SearchFeature/Sources/After/Components/AfterSearchComponent.swift
  Projects/Features/SearchFeature/Sources/After/Components/ListSearchResultComponent.swift
  Projects/Features/SearchFeature/Sources/After/Components/SearchOptionComponent.swift
  Projects/Features/SearchFeature/Sources/After/Components/SearchSortOptionComponent.swift
  Projects/Features/SearchFeature/Sources/After/Components/SongSearchResultComponent.swift
  Projects/Features/SearchFeature/Sources/After/CompositionalLayout/Layout/ListSearchResultCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/After/CompositionalLayout/Layout/SearchFilterOptionCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/After/CompositionalLayout/Layout/SongSearchResultCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/After/Reactors/AfterSearchReactor.swift
  Projects/Features/SearchFeature/Sources/After/Reactors/ListSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/After/Reactors/SongSearchResultReactor.swift
  Projects/Features/SearchFeature/Sources/After/View/ListResultCell.swift
  Projects/Features/SearchFeature/Sources/After/View/OptionButton.swift
  Projects/Features/SearchFeature/Sources/After/View/SearchFilterCell.swift
  Projects/Features/SearchFeature/Sources/After/View/SearchOptionHeaderView.swift
  Projects/Features/SearchFeature/Sources/After/View/SearchSortOptionCell.swift
  Projects/Features/SearchFeature/Sources/After/View/SongResultCell.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/AfterSearchViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/ListSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SearchSortOptionViewController.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
  Projects/Features/SearchFeature/Sources/Before/Components/BeforeSearchComponent.swift
  Projects/Features/SearchFeature/Sources/Before/Components/WakmusicRecommendComponent.swift
  Projects/Features/SearchFeature/Sources/Before/CompositionalLayout/Enum/DataSource/BeforeVcDataSoruce.swift
  Projects/Features/SearchFeature/Sources/Before/CompositionalLayout/Enum/Section/BeforeSearchSection.swift
  Projects/Features/SearchFeature/Sources/Before/CompositionalLayout/Enum/Section/ListSearchResultSection.swift
  Projects/Features/SearchFeature/Sources/Before/CompositionalLayout/Enum/Section/RecommendSection.swift
  Projects/Features/SearchFeature/Sources/Before/CompositionalLayout/Enum/Section/SongSearchResultSection.swift
  Projects/Features/SearchFeature/Sources/Before/CompositionalLayout/Layout/BeforeSearchCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/Before/CompositionalLayout/Layout/RecommendCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/Before/Reactors/BeforeSearchReactor.swift
  Projects/Features/SearchFeature/Sources/Before/Reactors/WakmusicRecommendReactor.swift
  Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Features/SearchFeature/Sources/Before/ViewControllers/WakmusicRecommendViewController.swift
  Projects/Features/SearchFeature/Sources/Before/Views/BeforeSearchSectionHeaderView.swift
  Projects/Features/SearchFeature/Sources/Before/Views/PopularPlayListCell.swift
  Projects/Features/SearchFeature/Sources/Before/Views/RecentRecordHeaderView.swift
  Projects/Features/SearchFeature/Sources/Before/Views/RecentRecordTableViewCell.swift
  Projects/Features/SearchFeature/Sources/Before/Views/YoutubeThumbnailCell.swift
  Projects/Features/SearchFeature/Sources/Root/Components/SearchComponent.swift
  Projects/Features/SearchFeature/Sources/Root/Reactors/SearchReactor.swift
  Projects/Features/SearchFeature/Sources/Root/ViewControllers/SearchViewController.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug

#842 🔀 :: (#841) 가사하이라이팅:: 곡에 따라 블러먹은 썸네일이 보이도록 변경
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController+Bind.swift
  Projects/Features/LyricHighlightingFeature/Sources/ViewControllers/LyricHighlightingViewController.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/LyricHighlighting.xcassets/error_dark.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/LyricHighlighting.xcassets/error_dark.imageset/error_dark@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/LyricHighlighting.xcassets/error_dark.imageset/error_dark@3x.png
Labels: 0️⃣ Priority: Critical, ✨ Feature

#855 🔀 :: (#854) 토스트 옵션 추가
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Modules/Utility/Sources/Enums/WMToastOptions.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIViewController.swift
Labels: ⚡️ Performance, 2️⃣ Priority: Medium

#858 🔀 :: (#850) WarningView 폰트 변경
  Projects/Features/BaseFeature/Sources/Views/WarningView.swift
  Projects/UsertInterfaces/DesignSystem/Sources/Views/WMWarningView.swift
Labels: ⚡️ Simple, 3️⃣ Priority: Low

#859 🔀 :: (#800) drag dismiss시 검은 배경 노출 오류 해결
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainContainerViewController.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#853 🔀 :: (#812) Credit Domain Interface 추가
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Credit.swift
  Projects/Domains/CreditDomain/Interface/UseCase/FetchCreditSongListUseCase.swift
  Projects/Domains/CreditDomain/Project.swift
  Projects/Domains/CreditDomain/Sources/UseCase/FetchCreditSongListUseCaseImpl.swift
  Projects/Domains/CreditDomain/Testing/UseCase/FetchCreditSongListUseCaseSpy.swift
  Projects/Domains/CreditDomain/Tests/CreditDomainTest.swift
Labels: 1️⃣ Priority: High

#860 🔀 :: (#849) 이미지 압축 80%를 진행합니다.
  Projects/Features/PlaylistFeature/Sources/Components/CheckThumbnailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/CheckThumbnailReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/DefaultPlaylistImageReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/CheckThumbnailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/MyPlaylistHeaderView.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#865 🔀 :: (#852) 플레이리스트 상세 페이지에서 로딩 전 EmptyView가 보이는 버그를 해결합니다.
  Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/WakmusicPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
Labels: 1️⃣ Priority: High, 0️⃣ Priority: Critical, 🐞 Bug

#867 🔀 :: (#866) 아티스트 상세:: 사이드 이펙트 오류 수정
  Projects/Features/ArtistFeature/Resources/Artist.storyboard
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Artist.xcassets/subscription_on.imageset/subscription_on@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Artist.xcassets/subscription_on.imageset/subscription_on@3x.png
Labels: 0️⃣ Priority: Critical, ⚡️ Simple, 🐞 Bug

#864 🔀 :: (#861) 커스텀 이미지 url 관련 api를 연결
  Projects/App/Sources/Application/AppComponent+Image.swift
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/Domains/BaseDomain/Interface/Enum/UploadImageType.swift
  Projects/Domains/PlaylistDomain/Interface/DataSource/RemotePlaylistDataSource.swift
  Projects/Domains/PlaylistDomain/Interface/Entity/CustomImageURLEntity.swift
  Projects/Domains/PlaylistDomain/Interface/Repository/PlaylistRepository.swift
  Projects/Domains/PlaylistDomain/Interface/UseCase/RequestCustomImageURLUseCase.swift
  Projects/Domains/PlaylistDomain/Interface/UseCase/UploadPlaylistImageUseCase.swift
  Projects/Domains/PlaylistDomain/Sources/API/PlaylistAPI.swift
  Projects/Domains/PlaylistDomain/Sources/DataSource/RemotePlaylistDataSourceImpl.swift
  Projects/Domains/PlaylistDomain/Sources/Repository/PlaylistRepositoryImpl.swift
  Projects/Domains/PlaylistDomain/Sources/RequestDTO/DefaultImageRequestDTO.swift
  Projects/Domains/PlaylistDomain/Sources/ResponseDTO/CustomImageURLResponseDTO.swift
  Projects/Domains/PlaylistDomain/Sources/UseCase/CheckSubscriptionUseCaseImpl.swift
  Projects/Domains/PlaylistDomain/Sources/UseCase/RequestCustomImageURLUseCaseImpl.swift
  Projects/Domains/PlaylistDomain/Sources/UseCase/UploadDefaultPlaylistImageUseCaseImpl.swift
  Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/UnkwonPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/DefaultPlaylistImageReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
Labels: 1️⃣ Priority: High, 🚀 API

#869 🔀 :: (#868) 팀 소개:: 데이터 구조 변경
  Projects/Domains/TeamDomain/Interface/Entity/TeamListEntity.swift
  Projects/Domains/TeamDomain/Sources/ResponseDTO/FetchTeamListResponseDTO.swift
  Projects/Features/TeamFeature/Interface/TeamInfoType.swift
  Projects/Features/TeamFeature/Sources/ViewControllers/TeamInfoContentViewController.swift
  Projects/Features/TeamFeature/Sources/ViewControllers/TeamInfoViewController.swift
  Projects/Features/TeamFeature/Sources/ViewModels/TeamInfoContentViewModel.swift
  Projects/Features/TeamFeature/Sources/ViewModels/TeamInfoViewModel.swift
Labels: ⚡️ Performance, ✨ Feature, 2️⃣ Priority: Medium

#873 🔀 :: (#863) 딥링크, 유니버셜링크 구현
  Projects/App/Sources/Application/AppComponent.swift
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Support/Info.plist
  Projects/App/Support/WaktaverseMusic.entitlements
  Projects/Features/MainTabFeature/Sources/AppEntryState/AppEntryState.swift
  Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+URL.swift
  Projects/Modules/Utility/Sources/Utils/Secrets.swift
Labels: 1️⃣ Priority: High, ✨ Feature

#880 🔀 :: (#871) 나만의 플레이리스트 이미지 api 적용
  Projects/Domains/BaseDomain/Sources/WMAPI/WMAPI.swift
  Projects/Domains/PlaylistDomain/Interface/Entity/CustomImageURLEntity.swift
  Projects/Domains/PlaylistDomain/Sources/API/CustomPlaylistImageAPI.swift
  Projects/Domains/PlaylistDomain/Sources/API/PlaylistAPI.swift
  Projects/Domains/PlaylistDomain/Sources/DataSource/RemotePlaylistDataSourceImpl.swift
  Projects/Domains/PlaylistDomain/Sources/UseCase/RequestCustomImageURLUseCaseImpl.swift
  Projects/Features/PlaylistFeature/Interface/DefaultPlaylistImageFactory.swift
  Projects/Features/PlaylistFeature/Sources/Model/PlaylistImageKind.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/UnknownPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/DefaultPlaylistImageViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
  Projects/Features/SearchFeature/Sources/Before/CompositionalLayout/Layout/BeforeSearchCollectionViewLayout.swift
  Projects/Features/SearchFeature/Sources/Before/ViewControllers/BeforeSearchContentViewController.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIImage.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UITableView.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#879 🔀 :: (#877) 아티스트:: 구독 상태 반영 오류 수정
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistDetailViewController.swift
  Projects/Features/ArtistFeature/Sources/ViewModels/ArtistDetailViewModel.swift
Labels: 1️⃣ Priority: High, 🐞 Bug

#883 🔀 :: (#882) 리사이징 로직 보완
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIImage.swift
Labels: 1️⃣ Priority: High, ⚡️ Performance

#886 🔀 :: (#884) MainTabFeature 디펜던시 정리
  Projects/App/Sources/Application/AppComponent+Artist.swift
  Projects/App/Sources/Application/AppComponent+Songs.swift
  Projects/Features/ArtistFeature/Interface/ArtistDetailFactory.swift
  Projects/Features/ArtistFeature/Interface/ArtistFactory.swift
  Projects/Features/ArtistFeature/Project.swift
  Projects/Features/ArtistFeature/Sources/Components/ArtistComponent.swift
  Projects/Features/ArtistFeature/Sources/Components/ArtistDetailComponent.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistViewController.swift
  Projects/Features/HomeFeature/Interface/HomeFactory.swift
  Projects/Features/HomeFeature/Project.swift
  Projects/Features/HomeFeature/Sources/Components/HomeComponent.swift
  Projects/Features/MainTabFeature/Project.swift
  Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
  graph.png
Labels: 1️⃣ Priority: High, ⚡️ Simple, ⚡️ Performance

#888 🔀 :: (#887) 앱 접속 시 유저 정보 셋팅
  Projects/Features/RootFeature/Sources/ViewModels/IntroViewModel.swift
Labels: 0️⃣ Priority: Critical

#885 🔀 :: (#881) 가격 api 연결 및 모호한 네이밍 변경
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Playlist.swift
  Projects/App/Sources/Application/AppComponent+Price.swift
  Projects/App/Support/Info.plist
  Projects/Domains/BaseDomain/Sources/WMAPI/SecretURL.swift
  Projects/Domains/BaseDomain/Sources/WMAPI/WMAPI.swift
  Projects/Domains/PriceDomain/Interface/DataSource/RemotePriceDataSource.swift
  Projects/Domains/PriceDomain/Interface/Entity/PriceEntity.swift
  Projects/Domains/PriceDomain/Interface/Repository/PriceRepository.swift
  Projects/Domains/PriceDomain/Interface/UseCase/FetchPlaylistCreationPriceUsecase.swift
  Projects/Domains/PriceDomain/Interface/UseCase/FetchPlaylistImagePriceUsecase.swift
  Projects/Domains/PriceDomain/Project.swift
  Projects/Domains/PriceDomain/Sources/DataSource/RemotePriceDataSourceImpl.swift
  Projects/Domains/PriceDomain/Sources/PriceAPI.swift
  Projects/Domains/PriceDomain/Sources/Repository/PriceRepositoryImpl.swift
  Projects/Domains/PriceDomain/Sources/ResponseDTO/PriceResponseDTO.swift
  Projects/Domains/PriceDomain/Sources/UseCase/FetchPlaylistCreationPriceUsecaseImpl.swift
  Projects/Domains/PriceDomain/Sources/UseCase/FetchPlaylistImagePriceUsecaseImpl.swift
  Projects/Features/BaseFeature/Project.swift
  Projects/Features/BaseFeature/Sources/Components/ContainSongsComponent.swift
  Projects/Features/BaseFeature/Sources/ViewControllers/ContainSongsViewController.swift
  Projects/Features/BaseFeature/Sources/ViewModels/ContainSongsViewModel.swift
  Projects/Features/MainTabFeature/Project.swift
  Projects/Features/PlaylistFeature/Interface/CheckThumbnailFactory.swift
  Projects/Features/PlaylistFeature/Interface/DefaultPlaylistImageFactory.swift
  Projects/Features/PlaylistFeature/Interface/PlaylistCoverOptionPopupFactory.swift
  Projects/Features/PlaylistFeature/Interface/ThumbnailPopupFactory.swift
  Projects/Features/PlaylistFeature/Sources/Components/CheckPlaylistCoverComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/CheckThumbnailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/DefaultPlaylistImageComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/PlaylistCoverOptionPopupComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/ThumbnailPopupComponent.swift
  Projects/Features/PlaylistFeature/Sources/Model/PlaylistCoverOptionModel.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/CheckPlaylistCoverlReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/DefaultPlaylistCoverReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/PlaylistCoverOptionPopupReactor.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/ThumbnailPopupReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/CheckPlaylistCoverViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/DefaultPlaylistCoverViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlaylistCoverOptionViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/ThumbnailOptionTableViewCell.swift
Labels: 1️⃣ Priority: High, 🚀 API

#893 🔀 :: (#892) 유니버셜링크 테스트 도메인 추가
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/App/Support/Info.plist
  Projects/App/Support/WaktaverseMusic.entitlements
  Projects/Modules/Utility/Sources/Utils/Secrets.swift
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Player.xcassets/dummy_thumbnail_large.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Player.xcassets/dummy_thumbnail_large.imageset/img.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Player.xcassets/dummy_thumbnail_large.imageset/img@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Player.xcassets/dummy_thumbnail_large.imageset/img@3x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Player.xcassets/dummy_thumbnail_medium.imageset/Contents.json
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Player.xcassets/dummy_thumbnail_medium.imageset/mediumdummy.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Player.xcassets/dummy_thumbnail_medium.imageset/mediumdummy@2x.png
  Projects/UsertInterfaces/DesignSystem/Resources/Image/Player.xcassets/dummy_thumbnail_medium.imageset/mediumdummy@3x.png
Labels: 0️⃣ Priority: Critical, ⚡️ Simple

#894 🔀 :: (#775) 유저 도메인 api 리스폰스 변경 대응 및 etc..
  Projects/App/Sources/Application/AppComponent+Auth.swift
  Projects/Domains/UserDomain/Interface/DataSource/RemoteUserDataSource.swift
  Projects/Domains/UserDomain/Interface/Repository/UserRepository.swift
  Projects/Domains/UserDomain/Interface/UseCase/DeleteFavoriteListUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/DeletePlaylistUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/EditFavoriteSongsOrderUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/EditPlaylistOrderUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/FetchFavoriteSongsUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/FetchUserInfoUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/SetProfileUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/SetUserNameUseCase.swift
  Projects/Domains/UserDomain/Interface/UseCase/WithdrawUserInfoUseCase.swift
  Projects/Domains/UserDomain/Sources/DataSource/RemoteUserDataSourceImpl.swift
  Projects/Domains/UserDomain/Sources/Repository/UserRepositoryImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/DeleteFavoriteListUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/DeletePlaylistUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/EditFavoriteSongsOrderUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/EditPlaylistOrderUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/FetchUserInfoUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/SetProfileUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/SetUserNameUseCaseImpl.swift
  Projects/Domains/UserDomain/Sources/UseCase/WithdrawUserInfoUseCaseImpl.swift
  Projects/Domains/UserDomain/Testing/WithdrawUserInfoUseCaseSpy.swift
  Projects/Features/MyInfoFeature/Sources/Components/RequestComponent.swift
  Projects/Features/MyInfoFeature/Sources/Reactors/SettingReactor.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Request/RequestViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewControllers/Setting/SettingViewController.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/ProfilePopViewModel.swift
  Projects/Features/MyInfoFeature/Sources/ViewModels/RequestViewModel.swift
  Projects/Features/MyInfoFeature/Sources/Views/SettingView.swift
  Projects/Features/StorageFeature/Sources/Reactors/LikeStorageReactor.swift
  Projects/Features/StorageFeature/Sources/Reactors/ListStorageReactor.swift
  Projects/Features/StorageFeature/Sources/ViewModels/AfterLoginStorageViewModel.swift
  Projects/Features/StorageFeature/Sources/ViewModels/FavoriteViewModel.swift
  Projects/Features/StorageFeature/Sources/ViewModels/MyPlayListViewModel.swift
  Projects/Features/StorageFeature/Sources/Views/LikeStorageView.swift
  Projects/Features/StorageFeature/Sources/Views/ListStorageView.swift
Labels: 1️⃣ Priority: High, 🚀 API

#891 🔀 :: (#889) 유니버셜 링크 공유하기
  Projects/Domains/PriceDomain/Project.swift
  Projects/Domains/SearchDomain/Interface/Entity/SearchPlaylistEntity.swift
  Projects/Domains/SearchDomain/Sources/DTO/SearchPlaylistDTO.swift
  Projects/Features/PlaylistFeature/Sources/Activity/PlaylistActivity.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/SearchFeature/Sources/After/View/ListResultCell.swift
  Projects/Modules/Utility/Sources/DeepLink/DeepLinkGenerator.swift
Labels: 1️⃣ Priority: High, ⚡️ Performance

#905 🔀 :: (#903) 최신음악:: 노래 상세 연결 외 1
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/Features/HomeFeature/Sources/Components/NewSongsContentComponent.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/HomeFeature/Sources/Views/NewSongsCell.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#904 🔀 :: (#902) 차트:: 노래 상세 연결
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/Features/ChartFeature/Sources/Components/ChartContentComponent.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/ChartFeature/Sources/Views/ChartContentTableViewCell.swift
  Projects/Features/HomeFeature/Sources/Components/NewSongsContentComponent.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/HomeFeature/Sources/Views/NewSongsCell.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#901 🔀 :: (#900) 아티스트 상세:: 노래 상세 연결
  Projects/App/Sources/Application/AppComponent+Songs.swift
  Projects/App/Sources/Application/SceneDelegate.swift
  Projects/Features/ArtistFeature/Resources/Artist.storyboard
  Projects/Features/ArtistFeature/Sources/Components/ArtistMusicContentComponent.swift
  Projects/Features/ArtistFeature/Sources/ViewControllers/ArtistMusicContentViewController.swift
  Projects/Features/ArtistFeature/Sources/Views/ArtistMusicCell.swift
  Projects/Features/BaseFeature/Sources/SongDetailPresenter/SongDetailPresenter.swift
  Projects/Features/ChartFeature/Sources/Components/ChartContentComponent.swift
  Projects/Features/ChartFeature/Sources/ViewContrillers/ChartContentViewController.swift
  Projects/Features/ChartFeature/Sources/Views/ChartContentTableViewCell.swift
  Projects/Features/HomeFeature/Sources/Components/NewSongsContentComponent.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/NewSongsContentViewController.swift
  Projects/Features/HomeFeature/Sources/Views/NewSongsCell.swift
  Projects/Features/MainTabFeature/Project.swift
  Projects/Features/MainTabFeature/Sources/Components/MainTabBarComponent.swift
  Projects/Features/MainTabFeature/Sources/ViewControllers/MainTabBarViewController.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#897 🔀 :: (#889) 검색, 플레이리스트 상세에 음악 상세 연결
  Projects/Features/PlaylistFeature/Project.swift
  Projects/Features/PlaylistFeature/Sources/Components/MyPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/UnkwonPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Components/WakmusicPlaylistDetailComponent.swift
  Projects/Features/PlaylistFeature/Sources/Reactors/MyPlaylistDetailReactor.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/PlayListViewController+Delegate.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/UnknownPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/WakmusicPlaylistDetailViewController.swift
  Projects/Features/PlaylistFeature/Sources/Views/PlaylistDateTableViewCell.swift
  Projects/Features/PlaylistFeature/Sources/Views/PlaylistTableViewCell.swift
  Projects/Features/SearchFeature/Project.swift
  Projects/Features/SearchFeature/Sources/After/Components/SongSearchResultComponent.swift
  Projects/Features/SearchFeature/Sources/After/View/SongResultCell.swift
  Projects/Features/SearchFeature/Sources/After/ViewControllers/SongSearchResultViewController.swift
Labels: 1️⃣ Priority: High, ⚡️ Performance

#906 🔀 :: (#812) Music Detail Feature 디렉토리 정리
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Sources/Application/AppComponent+Credit.swift
  Projects/App/Sources/Application/AppComponent+Songs.swift
  Projects/Features/CreditSongListFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Features/CreditSongListFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/CreditSongListFeature/Interface/Interface.swift
  Projects/Features/CreditSongListFeature/Project.swift
  Projects/Features/CreditSongListFeature/Sources/Sources.swift
  Projects/Features/CreditSongListFeature/Testing/Testing.swift
  Projects/Features/CreditSongListFeature/Tests/CreditSongListFeatureTest.swift
  Projects/Features/MusicDetailFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MusicDetailFeature/Sources/Karaoke/Component/KaraokeComponent.swift
  Projects/Features/MusicDetailFeature/Sources/Karaoke/KaraokeViewController.swift
  Projects/Features/MusicDetailFeature/Sources/Karaoke/Model/KaraokeKind.swift
  Projects/Features/MusicDetailFeature/Sources/Karaoke/Views/KaraokeContentView.swift
  Projects/Features/MusicDetailFeature/Sources/Karaoke/Views/KaraokeInfoView.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Component/MusicDetailComponent.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Model/SongModel.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailView.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailViewController.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicControlView/MusicControlGradientPanelLayer.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicControlView/MusicControlView.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicControlView/PlayMusicButtonGradientLayer.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicHeartButton/MusicHeartButton.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/MusicToolbarView.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/ThumbnailCollectionView/ThumbnailCell.swift
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/Views/ThumbnailCollectionView/ThumbnailCollectionView.swift
  Projects/Features/PlaylistFeature/Sources/ViewControllers/MyPlaylistDetailViewController.swift
  Projects/Features/SongCreditFeature/Interface/SongCreditFactory.swift
  Projects/Features/SongCreditFeature/Sources/Component/SongCreditComponent.swift
Labels: 1️⃣ Priority: High

#907 🔀 :: (#812) CreditDomain 구현
  Projects/App/Sources/Application/AppComponent+Credit.swift
  Projects/Domains/BaseDomain/Sources/WMAPI/SecretURL.swift
  Projects/Domains/BaseDomain/Sources/WMAPI/WMAPI.swift
  Projects/Domains/CreditDomain/Interface/CreditSongOrderType.swift
  Projects/Domains/CreditDomain/Interface/DataSource/RemoteCreditDataSource.swift
  Projects/Domains/CreditDomain/Interface/Repository/CreditRepository.swift
  Projects/Domains/CreditDomain/Interface/UseCase/FetchCreditSongListUseCase.swift
  Projects/Domains/CreditDomain/Sources/API/CreditAPI.swift
  Projects/Domains/CreditDomain/Sources/DataSource/RemoteCreditDataSourceImpl.swift
  Projects/Domains/CreditDomain/Sources/Repository/CreditRepositoryImpl.swift
  Projects/Domains/CreditDomain/Sources/ResponseDTO/FetchCreditSongListResponseDTO.swift
  Projects/Domains/CreditDomain/Sources/UseCase/FetchCreditSongListUseCaseImpl.swift
Labels: 1️⃣ Priority: High

#908 🔀 :: (#812) Credit Song List 화면 UI 구현
  Projects/App/Project.swift
  Projects/App/Sources/Application/AppComponent+Credit.swift
  Projects/Features/CreditSongListFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/CreditSongListFeature/Interface/CreditSongListFactory.swift
  Projects/Features/CreditSongListFeature/Interface/CreditSongListTabFactory.swift
  Projects/Features/CreditSongListFeature/Interface/CreditSongListTabItemFactory.swift
  Projects/Features/CreditSongListFeature/Interface/CreditSortType.swift
  Projects/Features/CreditSongListFeature/Interface/Interface.swift
  Projects/Features/CreditSongListFeature/Project.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongList/Component/CreditSongListComponent.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListReactor.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongList/CreditSongListViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongList/View/CreditProfileView.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/Component/CreditSongListTabComponent.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/Component/CreditSongListTabItemComponent.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/Model/CreditSongModel.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/View/CreditSongCollectionHeaderView.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/View/CreditSongCollectionViewCell.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/View/RandomPlayButton.swift
  Projects/Features/CreditSongListFeature/Sources/ScopedState/CreditSongListScopedState.swift
  Projects/Features/CreditSongListFeature/Sources/Sources.swift
  Projects/Features/SongCreditFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/SongCreditFeature/Project.swift
  Projects/Features/SongCreditFeature/Sources/Component/SongCreditComponent.swift
  Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
  Projects/Modules/Localization/Resources/en.lproj/Localizable.strings
  Projects/Modules/Localization/Resources/ko.lproj/Localizable.strings
  Projects/UsertInterfaces/DesignSystem/Sources/WMLabel.swift
Labels: 1️⃣ Priority: High

#913 🔀 :: (#910) Credit 작업자 노래 리스트 인터렉션 추가
  Projects/App/Support/Info.plist
  Projects/Features/BaseFeature/Sources/Protocols/SongCartViewType.swift
  Projects/Features/BaseFeature/Sources/Views/SongCartView.swift
  Projects/Features/CreditSongListFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/Component/CreditSongListTabItemComponent.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemReactor.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/CreditSongListTabItemViewController.swift
  Projects/Features/CreditSongListFeature/Sources/CreditSongListTab/View/CreditSongCollectionHeaderView.swift
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/SongCreditFeature/Sources/SongCreditViewController.swift
  Projects/Modules/Utility/Sources/Extensions/Extension+UIApplication.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature

#915 🔀 :: (#914) 홈 화면: 누락사항 반영
  Projects/Features/HomeFeature/Sources/ViewControllers/HomeViewController.swift
  Projects/Features/HomeFeature/Sources/ViewModels/HomeViewModel.swift
Labels: 0️⃣ Priority: Critical, ✨ Feature
