Repository wakmusic/wakmusic-iOS, pull requests merged in 2025-01, with the labels that each got.

#1334 🔀 :: (#1333) Xcode 16.2 호환 Realm 버전 업
  Cartfile
  Cartfile.resolved
Labels: 1️⃣ Priority: High, ⚡️ Simple

#1338 🔀 :: (#1337) CI runner 버전 업그레이드
  .github/workflows/CI.yml
Labels: 0️⃣ Priority: Critical, ⚙ Setting

#1336 🔀 :: (#1335) MusicDetailView crash 이슈 해결
  Projects/Features/MusicDetailFeature/Sources/MusicDetail/MusicDetailReactor.swift
Labels: 0️⃣ Priority: Critical, 🐞 Bug
